### ISSUE TITLE
Missing kernel module netdevsim

### ISSUE THREAD

**Issue by thediveo** [actions/runner-images#10134]
### Description

The `netdevsim` kernel module simulates network devices. In contrast to the so-called `dummy` kind network interfaces, netdevsims are actually virtual _devices_ and not just _network interfaces_. Kernel netdevsim goes back a long time, before 5.0 IIRC. netdevsim allows testing network interface testing with multiple queues, tc/XDP BPF and limited SR-IOV API aspects, but also PTP devices, without the need for a real physical HW NIC. netdevsims support aspects, `dummy` network interfaces do not.

In order to run tests relying on `netdevsim` being available and loadable, please consider adding the following kernel modules to Github runners:
- `netdevsim`
- `ptp_mock`
- `psample`

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Runner Image
  Image: ubuntu-22.04
  Version: 20240624.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240624.1/images/ubuntu/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240624.1

### Is it regression?

no

### Expected behavior

`modprobe netdevsim` succeeds

### Actual behavior

`modprobe: FATAL: Module netdevsim not found in directory /lib/modules/6.5.0-1022-azure`

### Repro steps

Have a Github action step:

```yaml
      - name: netdevsim kmodule
        run: sudo modprobe netdevsim
```

**Comment by ijunaidm** [comment]
Hi @thediveo, Thank you for bringing this issue to us, we are investigating on this issue and will update you after our findings.

**Comment by ijunaidm** [comment]
Hello @thediveo , Thank you for your feature request. We have investigated this feature request and unfortunately, we won't be able to accept it due to security and reliability risks.
All GitHub-owned Ubuntu images use official Azure Ubuntu image as a base image. Official Azure Ubuntu images have Azure-optimized kernel and we are not able to install any kernel modules on our images.

**Comment by thediveo** [comment]
Can you please elaborate how the netdevsim poses a security risk? The Linux kernel developers will be interested.

**Comment by ijunaidm** [comment]
@thediveo - The security risks associated with enabling the netdevsim module stem primarily from its capability to simulate network devices. While this is useful for development and testing, it can also potentially be exploited in environments where strict control over network interfaces is required.

For instance, netdevsim could be used to create simulated network devices that could bypass certain security policies or be used to interfere with the networking stack in unintended ways. In a multi-tenant environment, where different users share the same infrastructure, this could pose a risk by allowing one tenant to affect the network configuration or performance of another.

Additionally, ensuring the reliability of such a module across all the varied environments in which GitHub Actions run adds complexity, particularly when using an Azure-optimized kernel. Since our images are designed to be broadly applicable and secure across diverse workloads, introducing modules that may not be widely used or tested in these environments increases the potential for unforeseen issues.

Thank you.

**Comment by thediveo** [comment]
Then why you don't have all the other network devices disabled, such as VETH, MACVLAN, et cetera?

Thank you.

**Comment by ijunaidm** [comment]
@thediveo  - veth and macvlan: These modules are designed to operate within established security boundaries and are generally well-tested for safe use in containerized and virtualized environments. Their use is often tightly controlled and monitored to ensure they do not introduce significant security risks.
netdevsim: This module, due to its capability to simulate various network conditions and devices, presents a broader range of potential misuse or unintended consequences. It could potentially interfere with or disrupt the operation of other networked services if not properly contained.

Thank you, I hope i have answered your question.

**Comment by ijunaidm** [comment]
Hi @thediveo - Thank you , I am closing this ticket issue. Please feel free to open a new ticket if you face any issues related to the runner images.
