### ISSUE TITLE
AzureDevOps Windows 2019 - AZCopy missing

### ISSUE THREAD

**Issue by bartchojnacki** [actions/runner-images#10142]
### Description

Windows 2019 - according to the official documentation it's still there
https://github.com/actions/runner-images/blob/main/images/windows/Windows2019-Readme.md (azcopy 10.25.1) 
whilst in fact it  has been removed :
https://github.com/actions/runner-images/commit/89d72011e0cd8e10a4f178a194c04f873bf3757d

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240624.1.0

### Is it regression?

no

### Expected behavior

AZ copy present

### Actual behavior

AC copy missing

### Repro steps

 cd "C:\Program Files (x86)\Microsoft SDKs\Azure\AzCopy\"

**Comment by hemanthmanga** [comment]
@bartchojnacki We are looking into the issue, we will get back to you after investigating this issue, Thanks.

**Comment by kishorekumar-anchala** [comment]
Hi @bartchojnacki ,

  Could you please confirm What is the Azcopy version you're using ?

**Comment by bartchojnacki** [comment]
hi @kishorekumar-anchala ,
There is no version number available in the pre-update logs.
If i understand the agent specification correctly it used to be 10.25.1, although I presume it was was slightly older. The problem is that - since the agent runner update -  it's missing at all from "C:\Program Files (x86)\Microsoft SDKs\Azure" directory (can't see any version at all)

**Comment by kishorekumar-anchala** [comment]
Hi @bartchojnacki ,

1. The removal of AzCopy 8 from our images has impacted , but it was never explicitly installed and only came with Visual Studio 2019 as a dependency, which has now been removed due to its deprecation and lack of support. The Visual Studio team has confirmed they won't reintroduce it.
2. To ensure future compatibility, we advise transitioning to AzCopy 10, which is already installed and accessible.

Kindly refer below documentation:

[Migration Guide from AzCopy V8 to V10](https://github.com/Azure/azure-storage-azcopy/blob/main/MigrationGuideV8toV10.md)

[Troubleshooting and usage information for AzCopy](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/blobs/connectivity/storage-use-azcopy-troubleshoot)

**Comment by bartchojnacki** [comment]
Hi @kishorekumar-anchala  - that explains, thanks!
