### ISSUE TITLE
Ansible run command not found

### ISSUE THREAD

**Issue by xianlin** [actions/runner-images#10358]
### Description

Understand the ansible was installed via pipx but if we directly invoke `ansible` in the DevOps pipeline task, it will fail with message "ansible command not found". 

The only way to invoke the ansible is by put `export PATH="$PATH:/opt/pipx_bin"` ahead of the command.

Is this me or everyone must use ansible with self-hosted agent in this way? Thanks.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

N.A.

### Is it regression?

no

### Expected behavior

N.A.

### Actual behavior

N.A.

### Repro steps

N.A.

**Comment by xianlin** [comment]
Do we need to add `python3 -m pipx ensurepath` to ensure the pipx PATH is correctly setup on the Ubuntu OS?

**Comment by Prabhatkumar59** [comment]
Hi @xianlin - Thank you for bringing this issue to our attention. We will look into this issue and will update you shortly on this issue after investigating.

**Comment by Prabhatkumar59** [comment]
Hi @xianlin - The issue you're encountering, where the **ansible** command is not found, is due to the **pipx** installation directory not being included in the system PATH by default. When you install Ansible via **pipx**, it installs executables in a location (**/opt/pipx_bin**) that is not included in the PATH unless explicitly added.

You can try using below steps:-
A. **Add the pipx Bin Directory to the PATH**:

You can add the **pipx** bin directory to the PATH environment variable in your pipeline configuration. This ensures the **ansible** command is accessible.

```
export PATH="$PATH:/opt/pipx_bin"
ansible <your-ansible-command>
```
B. By Using **pipx ensurepath** to Automatically Set Up PATH:

You can run **python3 -m pipx** ensurepath to ensure that the **pipx** bin directory is added to the PATH environment variable. This command modifies your shell configuration to include the **pipx** bin directory in the PATH.
```
python3 -m pipx ensurepath
source ~/.bashrc  # or ~/.zshrc depending on your shell
```
So, Once this is done, the **ansible** command should be available without needing to manually export the PATH each time.

C. **Set Up PATH in Your DevOps Pipeline Configuration**:

If you are using a CI/CD pipeline, you can add a step to modify the PATH environment variable at the start of your pipeline script.
steps:
  ```
- script: |
      export PATH="$PATH:/opt/pipx_bin"
      ansible <your-ansible-command>
    displayName: 'Run Ansible Command'

```
By using above steps, it should get resolved.....thanks

**Comment by xianlin** [comment]
@Prabhatkumar59 , thank you but why we cannot make the PATH work for Ansible in the first place? I saw there is a `export PATH="$PATH:/opt/pipx_bin"` in the install-pipx-packages.sh script and that is why the Test script invoked in the same installation script succeeded.

Can we add the above PATH to the final image by using the `/scripts/helpers/etc-environment.sh` file? wouldn't it be better? thanks.

**Comment by Prabhatkumar59** [comment]
Hi @xianlin- Thanks for your response.
You can modify the **/scripts/helpers/etc-environment.sh** file to include the necessary PATH modification. This way, the PATH is set up correctly for all sessions, including new shell sessions.

Here’s how to modify the /**scripts/helpers/etc-environment.sh** file to include the pipx binary path:

A. **Steps to Modify /scripts/helpers/etc-environment.sh**
Open the /**scripts/helpers/etc-environment.sh** File:

Edit the **/scripts/helpers/etc-environment.sh** file to include the **pipx** binary path.

B. **Add the PATH Modification**:

Add the following lines to ensure the pipx binary directory is included in the PATH:

```
# Ensure pipx bin path is added to PATH
PIPX_BIN_PATH="/opt/pipx_bin"
if [ -d "$PIPX_BIN_PATH" ]; then
  echo "Adding pipx bin path to /etc/environment"
  # Append to the PATH variable in /etc/environment
  echo "PATH=\"\$PATH:$PIPX_BIN_PATH\"" >> /etc/environment
  export PATH="$PATH:$PIPX_BIN_PATH"
else
  echo "pipx bin path does not exist: $PIPX_BIN_PATH"
fi
```

C. **Build Custom Image**: Use the modified script during the image build process to ensure the PATH is correctly set.
D. **Verify in CI/CD Pipeline**: Check the PATH and ansible installation in the CI/CD pipeline to confirm everything is set up correctly.

By using above steps, you can ensure that the **pipx** binary path is correctly added to the PATH environment variable, making **ansible** accessible by default in all sessions.

**Comment by Prabhatkumar59** [comment]
Hi @xianlin - As I did not get any update from you. so, I am considering your issue is resolved and we are closing this issue. Please feel free to reach out to us in case of any query..thanks
