### ISSUE TITLE
Please provide a ubuntu-minimal image for Standard Runners

### ISSUE THREAD

**Issue by christopher-mullen** [actions/runner-images#10414]
### Description

There are existing issues calling out that GitHub actions can run out of space. An open example can be seen here
[https://github.com/actions/runner-images/issues/10386](https://github.com/actions/runner-images/issues/10386)

The solutions that users are coming up with involve removing packages from the runner. 

The alternative option would be to provide a minimal image - for example [https://wiki.ubuntu.com/Minimal](https://wiki.ubuntu.com/Minimal).

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Runner version: '2.317.0'
But could apply to any versions

### Is it regression?

Based on the job the action is performing.

### Expected behavior

Support for a smaller runner image that frees up more space on standard runners
Something like `runs-on: ubuntu-minimal`

### Actual behavior

Currently unavailable to select anything other than full-size ubuntu

### Repro steps

Create a GitHub Action.
Note the limited selection from https://github.com/actions/runner-images?tab=readme-ov-file#available-images

**Comment by RaviAkshintala** [comment]
@christopher-mullen Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by HinTak** [comment]
I found myself being affected by this - I am running a very large build job inside a fedora 40 docker container on ubuntu-latest.

The last round was successful 3 weeks ago after some careful clean up in between steps 
https://github.com/HinTak/Qt6WE-OT-SVG/actions/runs/10126487704 - and I had about 1 GB available space left. But somehow in last 3 weeks the available spaces at the beginning has dropped from over 19GB to below 17GB, so there is no way I can finish at the moment.

Unlike the others, since I am running a docker container inside ubuntu-latest, I can't clear up unbuntu-latest within the container - and I don't care about what is available under ubuntu-latest , since its role is only to load the docker image of another Linux.

**Comment by HinTak** [comment]
It seems to be getting worse - I checked my notes, 6 months ago the available space was in the region of 26GB. Is the runner image keeping a large apt-cache, for example? I seem to remember ubuntu systems can get progressively worse thar way over time.

**Comment by HinTak** [comment]
Okay, for my purpose, since I am just using the ubuntu runner to load a fedora docker container, what version of ubuntu doesn't matter to me. Just switching from ubuntu-latest (22.04) to ubuntu-24.04 gives me an extra 10 GB from just over 19GB to just over 30GB. 

I remember at some point in the last 12 months, ubuntu-latest gave me use of close to 26GB. There seems to be a gradual decline - it is probably the apt-cache.

**Comment by HinTak** [comment]
I am doing

```
    runs-on: ubuntu-24.04 # unbuntu-latest is 22.04
    container: fedora:40
```

so any clean-up of ubuntu can't be done.

**Comment by RaviAkshintala** [comment]
@christopher-mullen As of now there is no plans to provide ubuntu minimal image.Kindly please look into this [discussion](https://github.com/actions/runner-images/discussions/10332).We are closing this issue for now.Thanks.
