### ISSUE TITLE
Sysprep Error from RegDeleteValueW for value senseGuid

### ISSUE THREAD

**Issue by yo1-markenstein** [actions/runner-images#10434]
### Description

While generating windows2022 image using Azure DevOps during sysprep we get:
`Error SYSPRP ActionPlatform::DeleteValue: Error from RegDeleteValueW for value senseGuid under key HKEY_LOCAL_MACHINE\Software\Microsoft\Windows Advanced Threat Protection; dwRet = 0x5`

We suspect that during the provisioning a policy is applied on the VM that created the mentioned registry key before sysprep starts.
 
While searching for help we found issue #9499 which describes the same issue (second issue in that bug report). 
Apparently this issue is handled internally.
Can someone share the outcome of the internal resolution of issue #9499? Or otherwise provide a clue?

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Current image version: '1.0.460928'

### Is it regression?

no, we are setting up new pipeline

### Expected behavior

Expecting Sysprep to complete without error and able to instantiate VM from the generated image.

### Actual behavior

Sysprep step repeats displaying 'IMAGE_STATE_UNDEPLOYABLE' for several hours. Then the script finalizes and an image is created and stored in our compute gallery, but instantiating a VM from the image results in time-out.
(We added debug statement to display the content of Setuperr.log and break the build)

### Repro steps

- checkout runner-images repo in Azure DevOps pipeline
- run packer with a copy windows-2022.pkr.hcl while passing values for private network and a subscription/resourcegroup for which our company has VM policies in place.
- store the image in compute gallery.

**Comment by Prabhatkumar59** [comment]
Hi @yo1-markenstein - Thank you for bringing this issue to our attention. We will look into this issue and will update you on this issue after investigating.

**Comment by Prabhatkumar59** [comment]
Hi @yo1-markenstein - As I can see, for the Sysprep issue you're encountering error while generating a Windows 2022 image using Azure DevOps, here's a possible solution:-

**Root Cause:**
The error you mentioned (**Error SYSPRP ActionPlatform::DeleteValue**) indicates that during the provisioning process, a policy or a feature (likely related to Windows Defender or similar security software) is being applied, creating a registry key that conflicts with the Sysprep process.

**Suggested Workaround**:
**Disable the Security Software Temporarily**:

Before running Sysprep, disable or uninstall any security software (like Windows Defender or ATP) that might be applying policies or creating registry keys. This can be done via Group Policy or directly within the script if you have the necessary permissions.
**Manually Remove the Registry Key**:

You could manually remove the specific registry key (**senseGuid**) before running Sysprep. This could be scripted as part of the build process:-

`reg delete "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows Advanced Threat Protection" /v senseGuid /f
`
**Modify the Image Creation Script:**

If you have control over the image creation script, add a step to clean up any security-related registry keys before Sysprep runs.
**Verify and Update the Policies:**

Work with your IT or security team to ensure that any policies applied during provisioning are compatible with Sysprep, or adjust the timing of policy applications.
**Use a Custom Sysprep Answer File:**

If the above steps don't resolve the issue, consider using a custom Sysprep answer file that can handle or bypass these specific errors.

So, by using the above steps, it should help in mitigating the problem.

**Comment by yo1-markenstein** [comment]
Tanks @Prabhatkumar59 for digging to this.

I already tried to execute the sysprep with elevated permissions so I assumed that the Manually remove the key will not work also.

Regarding disable security software: we do execute the "[Configure-WindowsDefender.ps1](https://github.com/actions/runner-images/blob/main/images/windows/scripts/build/Configure-WindowsDefender.ps1)" script that seems to disable windows defender. Is that correct? Let me check if the policy that sets the key is executed after this script was executed.

If this doesn't help I will start conversation with our IT team to see if the temporary VM's created by Packer during provisioning can be excluded from applying the policie(s).

**Comment by Prabhatkumar59** [comment]
Hi @yo1-markenstein - Thanks for your response. I am providing you the updated recommendations below for your response.

**Updated Recommendations:**

**Verify Timing of Policy Application:**

It sounds like the "**Configure-WindowsDefender.ps1**" script should be disabling Windows Defender, but if the policy that sets the registry key is applied **after** this script runs, the key might still be created.

**Action**: Investigate the order of operations. Ensure that the "Configure-WindowsDefender.ps1" script runs after all policies have been applied. If needed, delay the script or re-run it just before **Sysprep** to ensure no policies re-enable Windows Defender or create new keys.

**Check Policy Enforcement:**
Confirm whether any Group Policies or security policies applied by your organization's IT infrastructure are enforced after the "**Configure-WindowsDefender.ps1**" script. These policies might be recreating the registry key or re-enabling certain features.
**Action**: If policies are being re-applied, consider coordinating with your IT team to temporarily lift those policies during the image creation process or adjust the timing to ensure they don't interfere with **Sysprep**.

**Try a Custom Script to Remove the Key:**
Since manually removing the registry key was suggested but might be seen as redundant given elevated permissions were used, try adding a custom script that explicitly checks and removes this key **immediately** before Sysprep runs.

For better understanding, I am providing an example as well as follows:-

**Script Example:**

```
# Check and remove the registry key before running Sysprep
$regPath = "HKLM:\Software\Microsoft\Windows Advanced Threat Protection"
$valueName = "senseGuid"

if (Test-Path $regPath) {
    Remove-ItemProperty -Path $regPath -Name $valueName -Force
}
```
**Review Sysprep Logs**:

Review the **Setuperr.log** and **Setupact.log** to confirm that there are no other underlying issues causing **Sysprep** to fail. This can provide additional insights into what might be going wrong during the process.

Hopefully, your issue should be resolved now.

**Comment by Prabhatkumar59** [comment]
Hi @yo1-markenstein- As I did not get any update from you so we are closing this issue, please feel free to reach out to us...thanks

**Comment by dzindzinj** [comment]
Hi,

Trying to create a new 2022 image using provided runner image steps. Sysprep errors at the same place as described in the main issue. The VM becomes unusable due to incomplete sysprep and we have to start again.
Unable to delete the value manually due to active Defender processes (access denied)


edit:
By adding following tags the issue is fixed. Azure was installing Defender for Cloud on the installer VM.
"ExcludeMdeAutoProvisioning": "True" 
https://github.com/orgs/community/discussions/160632
