### ISSUE TITLE
Run fails due to a bug

### ISSUE THREAD

**Issue by mathias-von-ottenbreit** [actions/runner-images#10461]
### Description

[This](https://github.com/ottenbreit-data-science/aplr/actions/runs/10308127056) ran successfully two weeks ago. However, [another](https://github.com/ottenbreit-data-science/aplr/actions/runs/10377520979) run on exactly the same code failed some days later. It looks like the successful run was using runner version 2.317.0 while the failing run used 2.319.0. The failing run failed on a macOS14 image, and it is unclear to me if it would also fail on other images (the run terminated as soon as the first image failed).

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

[Failed run](https://github.com/ottenbreit-data-science/aplr/actions/runs/10377520979)

### Is it regression?

Yes. [Latest successful run](https://github.com/ottenbreit-data-science/aplr/actions/runs/10308127056)

### Expected behavior

[This](https://github.com/ottenbreit-data-science/aplr/actions/runs/10308127056) run was successful. I expected that to happen.

### Actual behavior

Failed run.

### Repro steps

Run this [workflow](https://github.com/ottenbreit-data-science/aplr/actions/workflows/build_wheels.yml) on the main branch.

**Comment by sarathrajsrinivasan** [comment]
Hi @mathias-von-ottenbreit ,

We are looking into it. Will keep you posted with the updates.

**Comment by danmanners** [comment]
We're seeing the same behavior with both GitHub Hosted and Self-Hosted Ubuntu 22.04 runners after upgrading from v2.317.0 to v2.319.1.

**Comment by sarathrajsrinivasan** [comment]
Hi @mathias-von-ottenbreit and @danmanners ,

The above failure is not related to runner-images and looks like a dependency related issue. Please find our analysis below:

```
Error: TypeError: 'NoneType' object is not subscriptable (key slice(None, None, None))
in : pypy3.8/site-packages/setuptools/_distutils/unixccompiler.py
```

It seems at the point of failure self.linker_so_cxx is None, where it should be a list. 
https://github.com/pypa/distutils/blob/main/distutils/unixccompiler.py#L269

It could be due to a recent change in distutils and there is a similar issue reported here as well : https://github.com/pypy/pypy/issues/5004

We suspect there might be some changes in [pypa/cibuildwheel](https://github.com/pypa/cibuildwheel/releases) introduced in v2.18.0 and higher with respect to setuptools which could be causing the failure. 
```
uses: pypa/cibuildwheel@v2.17.0     --> Using this version Pipeline runs successfully.
```

We are closing the issue as this is not related to the macOS runner images.
