### ISSUE TITLE
Update Node to 18.20.4 in windows-2022 image

### ISSUE THREAD

**Issue by xinyi-joffre** [actions/runner-images#10596]
### Tool name

Node

### Tool license

N/A

### Add or update?

- [ ] Add
- [X] Update

### Desired version

18.20.4

### Brief description of tool

Is there an ETA for when node will be upgraded to 18.20.4 in the windows-2022 image?

We are getting alerts of vulnerabilities in 18.20.3 that were patched back in July 8 by node https://github.com/nodejs/node/releases/tag/v18.20.4. Thank you!

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by RaviAkshintala** [comment]
@xinyi-joffre Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by RaviAkshintala** [comment]
Hi @xinyi-joffre 

1. The Chaco packages do not have a version 18.20.4; the latest version in that series is 18.20.3, which is followed directly by 19.0.0. Kindly refer the [link](https://community.chocolatey.org/packages/nodejs.install#versionhistory).
2. In the README file, 18.20.3 is listed for Windows images because the 18 series is the default, indicating that 18.20.3 is the most recent version within that series.

**Comment by angaaruriakhil** [comment]
Hi, there is version 18.20.5 now available via [chocolatey](https://community.chocolatey.org/packages/nodejs.install#versionhistory), released on November 14. Also, I would say if chocolately doesn't serve the latest version of the software, that doesn't mean the software doesn't exist. We should not be putting our tools down. Other installation methods should be explored, otherwise we risk vulnerabilities being present in the image e.g. in this case CVE-2024-36138.

**Comment by Alexey-Ayupov** [comment]
Hello @xinyi-joffre, I believe this issue is no longer relevant as the image has an updated version. We have rewritten the installation script and are no longer dependent on `chocolatey`.

If you have any other questions feel free to reach us.
