### ISSUE TITLE
MacOS runners now always install the version of SwiftLint documented.

### ISSUE THREAD

**Issue by kimdv** [actions/runner-images#10595]
### Description

Documentation says that macOS 13 installs SwiftLint 0.56.2. 

But we got some runners that get 0.57.0. 

From what I can se [here](https://github.com/actions/runner-images/blob/ff9acc64011a3453c634ccfd271cae45a6c5a175/images/macos/scripts/build/install-swiftlint.sh#L4) it's because there is referred to a commit that target [`main`](https://raw.githubusercontent.com/Homebrew/homebrew-core/d91dabd087cb0b906c92a825df9e5e5e1a4f59f8/Formula/s/swiftlint.rb).
I will then assume it's the latest version that is released of SwiftLint. 

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [X] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: '2.319.1'

0.56.2: https://github.com/vippsas/vipps-ios-app/actions/runs/10814006698/job/29999383579
0.57.0: https://github.com/vippsas/vipps-ios-app/actions/runs/10813485617/job/29997625756

### Is it regression?

No

### Expected behavior

I will expect the version that is documented is the version that will be installed on the runners.

### Actual behavior

Sometimes we get the documented version other times we get the latest version.

### Repro steps

Run SwiftLint on a action and print version

**Comment by erik-bershel** [comment]
Hey @kimdv!

`macOS-13` image is in updating status: https://github.com/actions/runner-images?tab=readme-ov-file#available-images.
You may find the list of updates here: https://github.com/actions/runner-images/pull/10581.

We cannot update all agents at the same time and this process takes some time. Due to this, while the update is in progress, some tasks will fall on old agents, some on updated ones. This is not a bug, but normal behaviour.
