### ISSUE TITLE
Update .NET SDK 8 to 8.0.401 under ubuntu-24.04 to match 22.04

### ISSUE THREAD

**Issue by jupjohn** [actions/runner-images#10656]
### Tool name

.NET SDK 8

### Tool license

N/A

### Add or update?

- [ ] Add
- [X] Update

### Desired version

8.0.401 (matches ubuntu-22.04)

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by kishorekumar-anchala** [comment]
Hi @jupjohn ,

Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating

**Comment by jupjohn** [comment]
Thanks!

I upgraded an ADO pipeline today from `ubuntu-latest` (22.04) to 24.04 and noticed the SDK downgrade as my solution was pinned to 8.0.200 as minimum. I suspect others would have this issue as 24.04 gets rolled out as `ubuntu-latest` if this isn't upgraded.

**Comment by lakshminarayana02** [comment]
Dear @jupjohn 

We would like to inform you that the following.NET Core SDK versions available in Ubuntu 22.04 are  6.0.425, 7.0.410, and 8.0.401. However, Ubuntu 24.04 has not yet been rolled-out to General Availability and is scheduled to be released in the coming weeks.

Please let us know if you require any additional information to assist you, or allow us to close this issue.

**Comment by jupjohn** [comment]
Hey @lakshminarayana02, 

Maybe the description was confusing: I am suggesting to have the .NET 8 SDK on `ubuntu-24.04` upgraded to be in line with what `ubuntu-22.04` has before it goes GA. I don't see a reason for it to be using `8.0.1xx` when most users have been using `8.0.4xx` provided by default.

**Comment by lakshminarayana02** [comment]
Hi @jupjohn 
Yes, it will take a few more weeks to be accessible for GA.  
 Ubuntu 24.04 will always provide the most recent updates and stable versions with the default version. 

If you are satisfied with the solution, kindly suggest that we close this ticket.

**Comment by thommaa** [comment]
Hi @lakshminarayana02,

could you please rerun the image generation pipeline for Ubuntu 24.04 as for which ever reason the dotnet sdk has built as  .NET Core SDK: 8.0.108
https://github.com/actions/runner-images/blob/8a1eeaf6ac70c66f675a04078d1a7222edd42008/images/ubuntu/Ubuntu2404-Readme.md?plain=1#L160

the pipeline definitions should pull this through properly.

**Comment by lakshminarayana02** [comment]
Dear @thommaa
Yes, we noticed that the previous and current Image Generation builds have the same version,  we are working to fix the issue.

**Comment by ThibaultLesuisse** [comment]
Don't really know how you are going to pull this off. Ubuntu 24.04 won't add any version beyond 8.0.10* and Microsoft won't provide them in their repo's as described [here](https://github.com/dotnet/core/discussions/9258). So the only option left is to install the SDK by using the dotnet install scripts.

**Comment by lakshminarayana02** [comment]
Hi
While investigating,  we noticed line 65. . The link is maintained by Microsoft.
https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-dotnetcore-sdk.sh#L65

We are attempting to gather more information and will share it here.

**Comment by lakshminarayana02** [comment]
Hi 
we are still working on it and will keep you posted,

**Comment by lakshminarayana02** [comment]
Hi
SDK version in all the latest images have been upgraded from 8 to 8.0.40x version EXCEPT for Ubuntu-24 which shows 8.0.10x version and it will be updated in current week deployment. 

Thank you for contacting us,  we have rectified this issue.

**Comment by mario-d-s** [comment]
@lakshminarayana02 this issue was marked as resolved but it doesn't seem to be the case.

The 20241103 release of **this** week [still mentions .NET Core SDK: 8.0.110 only](https://github.com/actions/runner-images/blob/releases/ubuntu24/20241103/images/ubuntu/Ubuntu2404-Readme.md#net-tools). And since this document is [generated by script](https://github.com/actions/runner-images/blob/bf6ac0db939ae88ee1b48cdde887372aeab75b3f/images/ubuntu/scripts/docs-gen/Generate-SoftwareReport.ps1#L231) directly on a VM that serves as the basis for the image, it's not a matter of someone having forgotten to update the documentation - this reflects what is present on the actual agents.

We're building our own agents loosely based on the scripts in this repo and it just seems that the [install-dotnetcore-sdk.sh](https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-dotnetcore-sdk.sh) script is broken for Ubuntu 24.04. I identify 2 issues:
* SDK tarballs are downloaded to `/tmp` but the `find` command that should execute `extract_dotnet_sdk` on the files [looks in the working directory (`.`)](https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-dotnetcore-sdk.sh#L85). I don't see where the working directory is set to `/tmp` in the Packer template or any preceding scripts, but I might be missing something.
* More importantly, the `extract_dotnet_sdk` function tries to install SDKs to `/usr/share/dotnet` while the official Ubuntu package for `dotnet-sdk-8.0` on 24.04 installs to `/usr/lib/dotnet`. Since `/usr/share/dotnet` does not exist, rsync fails to move the files.

Furthermore, the script unconditionally applies steps for pinning the package sources to the Microsoft repositories which only applies to Ubuntu 22.04 (and maybe 20.04, I don't know). There are conflicting sources of information on whether the Microsoft package repositories for Ubuntu 24.04 provide `*net*` packages but it turns out they **do not** as mentioned in dotnet/core/discussions/9258.
