### ISSUE TITLE
sudo apt-get update in ubuntu error 404 Not Found [IP: 185...]

### ISSUE THREAD

**Issue by Khacduy618** [actions/runner-images#10662]
### Description

Hit:1 http://archive.ubuntu.com/ubuntu noble InRelease
Hit:2 http://archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu noble-security InRelease
Ign:4 http://archive.canonical.com/ubuntu noble InRelease
Hit:5 http://archive.ubuntu.com/ubuntu noble-backports InRelease
Err:6 http://archive.canonical.com/ubuntu noble Release
  404  Not Found [IP: 185.125.188.12 80]
Reading package lists... Done
E: The repository 'http://archive.canonical.com/ubuntu noble Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

.

### Is it regression?

.

### Expected behavior

.

### Actual behavior

.

### Repro steps

.

**Comment by vidyasagarnimmagaddi** [comment]
Hi @Khacduy618 ,Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by Prabhatkumar59** [comment]
Hi @Khacduy618 - From your above issue description, i can clearly se that the error occurs because the **noble** codename in the repository URLs is invalid. It seems there was a typo or misconfiguration. The correct codename for Ubuntu 24.04 should be **mantic** (assuming you're referring to the latest development release), or another valid codename like **jammy** for Ubuntu 22.04.

**For you, i am providing some steps to resolve it as follows:-**

A. Check /etc/apt/sources.list: Open the file where your repositories are listed and look for entries referring to noble.
`sudo nano /etc/apt/sources.list
`
B. You can try to replace **noble** with **mantic**: Replace all instances of noble with the correct release codename, such as **mantic**, for the Ubuntu 24.04 release or another appropriate version.
Replace below
`http://archive.ubuntu.com/ubuntu noble InRelease
`
with 
`http://archive.ubuntu.com/ubuntu mantic InRelease
`
C. Also, If you are deploying Ubuntu instances programmatically, ensure that your automation scripts or image generation tools refer to the correct codename (e.g., **mantic or another supported version).**

You can also remove the problematic repository if it’s no longer needed as below:-

`sudo add-apt-repository --remove 'http://archive.canonical.com/ubuntu noble'`
The repository URL with the codename **noble** does not exist, hence the 404 Not Found error.

So, fixing the sources list and replacing **noble** with the correct codename should resolve the issue you are facing. And hopefully these changes will resolve your issue.

**Comment by Prabhatkumar59** [comment]
Hi @Khacduy618 - Since we haven't heard back, we'll assume your issue is resolved and will close this issue for now. Feel free to reach out to us for any other queries. Thanks.
