### ISSUE TITLE
[macos14] xcodebuild Resolve Package Graph freezes Runner

### ISSUE THREAD

**Issue by basvankuijck** [actions/runner-images#10722]
### Description

We've been experiencing this behaviour on some of our (private) projects.
And the workflow seems to freeze during the "Resolve Package Graph" phase.
Everytime at a different package:

```
...
INFO [2024-10-02 06:32:43.30]: ▸ Creating working copy of package ‘promises’
INFO [2024-10-02 06:32:43.33]: ▸ Checking out 2.4.0 of package ‘promises’
```

Also came across identical issues: 
- https://github.com/actions/runner-images/issues/6233
- https://github.com/mParticle/mparticle-apple-sdk/issues/191

I tried to solve it with the ".netrc" fix, but that didn't have any effect.

It could be related to a similar dialog popping up:

![](https://user-images.githubusercontent.com/5477014/236261657-a6d9a1a1-dbf5-472a-9e3f-83eb72efea53.png)

---

I made a simple pipeline that mimics the behaviour.
It uses fastlane to build the app, for now it just hangs on the `xcodebuild -showBuildSettings` step.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20240922.1

- https://github.com/UnlockAgency/RunnerTest/actions/runs/11138951426/job/30954763325
- https://github.com/UnlockAgency/RunnerTest/actions/runs/11138724140/job/30954171807
- https://github.com/UnlockAgency/RunnerTest/actions/runs/11133326526/job/30939168451

### Is it regression?

No

### Expected behavior

That the build would proceed as intented

### Actual behavior

The runner seems to freeze. Only possible step is to cancel the run or wait for the timeout to kick in.

### Repro steps

Run the workflow manually

**Comment by erik-bershel** [comment]
Hey @basvankuijck!

If it's the same bug, we won't be able to affect it from our side. You say you tried the workaround? Let's synchronise our clocks. Here are the ones I found:
- Add a bash step in your workflow that runs echo -e "machine [github.com](http://github.com/)\n  login oauth2\n  password $GITHUB_TOKEN\n\n" > ~/.netrc and echo -e "machine [apt.github.com](http://apt.github.com/)\n  login oauth2\n  password $GITHUB_TOKEN\n\n" > ~/.netrc ([ref](https://forums.swift.org/t/support-for-resolving-private-packages-through-https-with-xcodebuild/48581/12)). You’ll need to make GITHUB_TOKEN available to the env with GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
- Or, use the below third-party action to do the same:
```yml
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/netrc@v1
        with:
          machine: github.com
          username: oauth2
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: extractions/netrc@v1
        with:
          machine: api.github.com
          username: oauth2
          password: ${{ secrets.GITHUB_TOKEN }}
```

One of those should definitely resolve the issue with `.netrc`. Can you update the issue with the example project to run provided command over it if workaround didn't work?

**Comment by basvankuijck** [comment]
I updated the workflow to use the `extractions/netrc@v1` actions.
But the outcome is the same: https://github.com/UnlockAgency/RunnerTest/actions/runs/11140794213/job/30960337171

Apart from the fact that the package that causes the freeze differs per build.

All the packages used are on github repositories: https://github.com/UnlockAgency/RunnerTest/blob/main/RunnerTest.xcworkspace/xcshareddata/swiftpm/Package.resolved

**Comment by erik-bershel** [comment]
Yeah, seems it require a bit of investigation. 🥸 We will get back to you later with updated information.

**Comment by basvankuijck** [comment]
I did some digging as well and found out that `xcodebuild` actually has a setting to listen for .netrc authorization instead of keychain.
So I added `-scmProvider system -packageAuthorizationProvider netrc` to my xcodebuild command:

```
xcodebuild -workspace '../RunnerTest.xcworkspace' \
-scheme 'RunnerTest (accept)' \
-configuration 'Adhoc' \
-showBuildSettings \
-verbose \
-scmProvider system \
-packageAuthorizationProvider netrc
```

And now it seems to work: https://github.com/UnlockAgency/RunnerTest/actions/runs/11143212632/job/30967793387

**Comment by erik-bershel** [comment]
Hey @basvankuijck! I am going to close this issue as Xcode build configuration related which is not a part of image generation anyway. Glad you found a solution - I hope it will help other users who met the same issue.

**Comment by eseay** [comment]
@erik-bershel I just came across this discussion after struggling with this same issue for quite some time, ultimately giving up and settling on remaining on Xcode 15.4 for the time being, and eventually picking it back up.

My dependency setup and Actions workflow configuration has been the same for some time - including `.netrc` setup and some other auth setup steps to allow the runner to authenticate properly. **With Xcode 15.4, everything was working**. Only when moving to Xcode 16.x did things break.

Based on my investigation, it appears that this issue surfaces itself specifically when your Swift Package dependency list includes BOTH:
- A private Swift Package
- A _binary_ package dependency

Which is to say - it doesn't occur when you have binary dependencies + standard public packages, or standard public packages + standard private packages.

Ultimately **the solution that @basvankuijck noted above ended up working**, so my problem is solved, but I think it's worth mentioning that this is completely non-obvious behavior with a completely non-obvious solution, and the issue _appears_ as though it's Actions-specific, when in actuality, it's just a matter of how Xcode is set up on the virtual runner.

I'm bringing this up because I think it would be worth officially including somewhere in the GitHub Actions documentation or at least a blog post the instructions for how to set up `.netrc` and which args you need to pass to `xcodebuild`, because the project configuration that causes it isn't really that weird, yet the solution is very challenging to discover. 

Thanks!

**Comment by christophby** [comment]
None of the above fixed the issue for me **but this did**:

Adding an extra _resolve dependencies_ step before my actual fastlane (build app) step.
Plus: Add the `SWIFTPM_MAX_CONCURRENT_OPERATIONS` env var

```yml
 - name: 📦 iOS - Pre-resolve Swift packages to
        run: |
          env SWIFTPM_MAX_CONCURRENT_OPERATIONS=1 xcodebuild -resolvePackageDependencies -workspace ios/yourWorkSpaceName.xcworkspace -scheme yourSchemeName

```

**Comment by MutinyHCF** [comment]
I was hitting this when running both the Xcode task as well as xcodebuild through the bash task; turned out to be an auth issue with SwiftPM needing the .netrc file with an Auth Token for GitHub.

This was strange pretty hard to track down with the lack of logging output, because my project was already successfully using other SwiftPM dependencies hosted in Github.

+1 on the comment from @eseay for this being added to documentation
