### ISSUE TITLE
Ubuntu build failing with Script disconnected unexpectedly

### ISSUE THREAD

**Issue by gavintoddchurch** [actions/runner-images#10757]
### Description

I'm not 100% sure but i'm pretty sure i've seen it get the error during intall-apt-common. The latest failur was during the install-clang.sh

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Failing during image creation

### Is it regression?

Yes, worked 2 days ago

### Expected behavior

Image builds succesfully

### Actual behavior

Errors out with disconnect error

### Repro steps

Clone runner-images repo
attempt to build ubuntu 22.04 image

**Comment by Prabhatkumar59** [comment]
Hi @gavintoddchurch - Thank you for bringing this issue to our attention. We will look into this issue and will update you on this issue after investigating.

**Comment by gavintoddchurch** [comment]
Thank you! I tested today and i'm still experiencing the same issue. Latest failure was in install-apt-common.sh

**Comment by Prabhatkumar59** [comment]
Hi @gavintoddchurch - we will check into this and will update you after investigating.Thanks!

**Comment by Prabhatkumar59** [comment]
Hi @gavintoddchurch - As per my investigation and understanding, the "Script disconnected unexpectedly" error more likely comes from network issues, limited resources (like memory or disk space), or problems with package installations during the build.
In order to fix it, make sure that the network is stable and add retries to **apt-get install** commands.
You can also try by free up space before running the install commands.
You can also retry failed **apt-get** commands to avoid conflicts.
Additionally, you can try to add more debug logs around the apt-get install commands.
As you mentioned, since the issue worked fine 2 days ago, please check if there have been any recent changes in the script, environment configuration, or network settings.

Requesting you to try these and update me on this. Thanks!

**Comment by gavintoddchurch** [comment]
I have been trying further attempts but it has been a couple days now. Doesn't the scripts create its own rg, vnet, vm, etc to create the image so it should all be using Azures default networking?

**Comment by Prabhatkumar59** [comment]
And for your this reply https://github.com/actions/runner-images/issues/10757#issuecomment-2419843577 - As I can observe, the build script is getting disconnected while configuring **apt**. As per my understanding and investigation,  it's likely due to network problems, resource limitations, or timeouts.

For this, you can try to update the script settings to handle expected disconnections by adding "expect_disconnect": true or "valid_exit_codes": [0, 2300218]

You can also add retries to the **apt-get** commands in **configure-apt.sh** to handle intermittent network issues. Providing below bash example for you, 
for i in {1..5}; do
    apt-get update && apt-get install -y jq && break || sleep 15
done
In this example, Set a higher timeout for the **apt-get** operations to avoid disconnecting due to delays.
These might help avoid unexpected disconnections during the build process.

Please let me know once after trying these as well. Thanks!

**Comment by gavintoddchurch** [comment]
I've probably tried this 30+ times on various days, times, etc over the last week or 2. I've looked and there are no Azure impacts in the region that I have seen. 

The issue with adding retries is this fails randomly through the scripts. It happens in apt-common, docker, dotnet, powershell, etc. so i would have to add retries to every script.

I've never had this issue with the default vm size and i'm not adding anything additional to the agents so space shouldn't be an issue. 

How would I turn on Azure diagnostics?

Are you experiencing the issue? I'm not sure how I could be the only one seeing this issue.

**Comment by gavintoddchurch** [comment]
I finally got this to work but on a different machine. I'm not sure what is interrupting the process on this computer. Thank you for helping and make sure everything was working correctly.
