### ISSUE TITLE
msvc command line tools are not on %PATH%

### ISSUE THREAD

**Issue by bnoordhuis** [actions/runner-images#10853]
### Description

Sorta similar to #6205 but I can offer a few more observations:

1. Trying to invoke cl.exe (and presumably ld.exe etc.) directly right now is... I didn't manage to get it working in https://github.com/quickjs-ng/quickjs/pull/615 and I believe I qualify as at least moderately competent. It's definitely harder than it should be. The "ordained" way (according to search engines: use hard-coded paths to the current msvc point release) is extremely brittle.

2. clang-cl.exe, the cl.exe-compatible frontend for clang, _is_ on the path. I'm not complaining but that seems inconsistent.

Maybe there's an easy and robust way to accomplish running cl.exe. In that case I would be grateful for improved documentation.

Blame where blame is due: I expected vcvarsall.bat to update %PATH% but it doesn't.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

n/a

### Is it regression?

Has always been broken AFAICT

### Expected behavior

n/a

### Actual behavior

n/a

### Repro steps

n/a

**Comment by sean-mcmanus** [comment]
I believe this is "by design". I think you're expected to run vcvarsall.bat and pass arguments like amd64_arm64, x64, -vcvars_ver=14.41, etc. to control which of the many possible installed cl.exe versions are used.

**Comment by Prabhatkumar59** [comment]
Hi @bnoordhuis - Thank you for bringing this issue to our attention. We will look into this issue and will update you on this issue after investigating.

**Comment by bnoordhuis** [comment]
As another data point: we finally got it working but only after pulling in https://github.com/egor-tensin/vs-shell

**Comment by Prabhatkumar59** [comment]
Hi @bnoordhuis - Thanks for your input! So, just to confirm, is it working fine for you and your issue got resolved?

**Comment by bnoordhuis** [comment]
I wouldn't call it resolved; we found a workaround. You could summarize my original report as "invoking cl.exe is too darn hard" and that didn't change.

**Comment by bnoordhuis** [comment]
Original report as in https://github.com/actions/runner-images/issues/10853#issue-2609660304

**Comment by Prabhatkumar59** [comment]
Thanks @bnoordhuis your reply. I will check and update for "invoking cl.exe".

**Comment by Prabhatkumar59** [comment]
Hi @bnoordhuis - As per your issue description, i can summarise that invoking **cl.exe** is overly complicated and not easy though. Despite finding a workaround using **vs-shell**, the core challenge of setting up a straightforward, reliable environment for **msvc** tools remains unresolved."

However, as per my observation, in order to resolve the issue of msvc command line tools not being on %PATH%, you can try to use the following possibilities:-

- You can try to manually Set Up the Environment Using vcvarsall.bat.
- Also please make sure cl.exe is executed in the same shell session where vcvarsall.bat was called. This ensures that the environment variables set by vcvarsall.bat are available

These possible ways might be able to invoke cl.exe without relying on hard-coded paths.

**Comment by Prabhatkumar59** [comment]
Hi @bnoordhuis - Since we haven't heard back, we'll assume your issue is resolved and will close this issue for now. Feel free to reach out to us for any other queries. Thanks.
