### ISSUE TITLE
DNS issues

### ISSUE THREAD

**Issue by rowleya** [actions/runner-images#10911]
### Description

We seem to periodically get issues resolving web sites on some run runs.  This appears completely random on different operating systems, though it appears to be almost constant on macOS and less often on Ubuntu and very infrequently on Windows. 

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

On Ubuntu 22.04, last encountered: 20241015.1.0 (https://github.com/SpiNNakerManchester/sPyNNaker/actions/runs/11700388899/job/32584448086)
On Windows Server 2022, last encountered: 20241021.1.0 (https://github.com/SpiNNakerManchester/sPyNNaker/actions/runs/11660030018/job/32462691344)
On MacOS 14 Arm64, last encountered (note this run is disabled now as it happens so often):  20240818.4 (https://github.com/SpiNNakerManchester/sPyNNaker/actions/runs/10593826135/job/29357835356)

### Is it regression?

Not obvious - possibly not

### Expected behavior

DNS lookup succeeds on every run!

### Actual behavior

DNS lookup fails randomly.

### Repro steps

Run actions; could probably re-run some of our actions as linked above, but it is random...

**Comment by vaishalipawar1490** [comment]
Hi @rowleya , 
It seems to be that the issue you’re experiencing might be related to the DNS configuration for the domain spinnaker.cs.man.ac.uk, rather than an issue with the macOS latest environment itself. Sometimes, DNS misconfigurations or issues on the DNS server side can cause the problems. Could you please check on your end to ensure there are no DNS related issues? We’re also looking into it from our side to confirm there are no additional factors involved.

**Comment by vaishalipawar1490** [comment]
Hi @rowleya,
Since there is no further action pending from our end we are closing this issue for now. Please feel free to reach out if you’ve any further questions. Thanks.
