### ISSUE TITLE
[MacOS] Add label for using the latest macOS version with x86_64 architecture

### ISSUE THREAD

**Issue by altinokdarici** [actions/runner-images#11109]
### Description

Currently, the macos-latest label points to an ARM-based macOS environment. However, our workflows need to run on both ARM and x86_64 architectures. While macos-latest covers ARM, there is no equivalent label for the latest x86_64-based macOS. As a result, we must manually track and update the latest available x86_64 macOS version by referring to GitHub documentation, which adds unnecessary maintenance overhead.

A macos-x86_64-latest label would streamline this process and ensure compatibility across architectures.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

N/A

### Is it regression?

No

### Expected behavior

A macos-x86_64-latest label should be available, allowing workflows to automatically run on the latest x86_64-based macOS without manual version updates. This would ensure consistency and reduce maintenance efforts for keeping workflows compatible across both ARM and x86_64 architectures.

### Actual behavior

Currently, only the macos-latest label is available, which points to an ARM-based macOS environment. There is no equivalent label for the latest x86_64-based macOS, requiring manual tracking and updates to use the most recent version.

### Repro steps

N/A

**Comment by aartis17** [comment]
Hi @altinokdarici ,
We will look into the issue and keep you posted with updates.
Thank you.

**Comment by erik-bershel** [comment]
Hey @altinokdarici!

Unfortunately, we are unable to service your request. All the supported runners described [here](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) and [here](https://github.com/actions/runner-images?tab=readme-ov-file#available-images). Adding an architectural reference does not make sense due to the transition to `Apple Silicon` as the main platform for `macOS`. Runners based on `Intel` processors are available starting with `macOS-14` only as `macos-<version>-large` aka `Larger Runners` for `GitHub Actions` users.
There are currently no plans to provide these runners on top of the `Standard Runners`. If such plans appear, we will notify the community.
