### ISSUE TITLE
Add NuGet Package Manage Utility to Ubuntu 24.04 Repository

### ISSUE THREAD

**Issue by YaseenKaddouri-NewDay** [actions/runner-images#11138]
### Tool name

Require NuGet on Ubuntu 24.04 Debian Repository

### Tool license

open-source

### Add or update?

- [X] Add
- [ ] Update

### Desired version

NuGet 6.9

### Brief description of tool

The latest version of the Ubuntu images used for the GitHub hosted runners (24.04) does not include NuGet. We would like this to be added if possible thank you.

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by kishorekumar-anchala** [comment]
Hi @YaseenKaddouri-NewDay ,

Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating

**Comment by lakshminarayana02** [comment]
Dear @YaseenKaddouri-NewDay 

Thank you for contacting us regarding the Nuget package in Ubuntu 24. The Nuget package is available in Ubuntu 20 and 22 images.

We understand the advantages of the Nuget package, however we decided to remove some tools in order to maintain a lightweight OS image. We recommend that you install it in build runtime and use it. 

We will take your request into consideration if there is a future demand for this tool from more users.
