### ISSUE TITLE
`dotnet restore` failes `Unable to load shared library 'libdl' or one of its dependencies`

### ISSUE THREAD

**Issue by HofmeisterAn** [actions/runner-images#6029]
### Description

[DotNetRestore](https://cakebuild.net/api/Cake.Common.Tools.DotNet/DotNetAliases/26E59D8B) failes with following error [message](https://github.com/testcontainers/testcontainers-dotnet/runs/7703734540?check_suite_focus=true#step:5:12): `Unable to load shared library 'libdl' or one of its dependencies`.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

[20220731.1](https://github.com/testcontainers/testcontainers-dotnet/runs/7703734540?check_suite_focus=true#step:1:9) (ubuntu-22.04)

### Is it regression?

[20220729.1](https://github.com/testcontainers/testcontainers-dotnet/runs/7676537954?check_suite_focus=true#step:1:9) (ubuntu-20.04)

### Expected behavior

~~`dotnet restore` succeed~~
[DotNetRestore](https://cakebuild.net/api/Cake.Common.Tools.DotNet/DotNetAliases/26E59D8B) succeed

### Actual behavior

~~`dotnet restore` fails~~
[DotNetRestore](https://cakebuild.net/api/Cake.Common.Tools.DotNet/DotNetAliases/26E59D8B) fails

### Repro steps

- ~~`dotnet restore Testcontainers.sln`~~
- Pipeline [step](https://github.com/testcontainers/testcontainers-dotnet/blob/develop/.github/workflows/cicd.yml#L47) runs [Restore-NuGet-Packages](https://github.com/testcontainers/testcontainers-dotnet/blob/develop/build.cake#L43) (`DotNetRestore`)

**Comment by igorboskovic3** [comment]
Hi @HofmeisterAn thank you for reporting this one, we will take a look.

**Comment by al-cheb** [comment]
Hello, @HofmeisterAn.
I see you changed hosted-agent version from ubuntu 20.04 -> 22.04.

Ubuntu Server 20.04 has libc 2.31 version:
```
ii  libc-dev-bin                                                2.31-0ubuntu9.9                                                      amd64        GNU C Library: Development binaries
ii  libc6:amd64                                                 2.31-0ubuntu9.9                                                      amd64        GNU C Library: Shared libraries
ii  libc6-dev:amd64                                             2.31-0ubuntu9.9                                                      amd64        GNU C Library: Development Libraries and Header Files
ii  libc6-i386                                                  2.31-0ubuntu9.9                                                      amd64        GNU C Library: 32-bit shared libraries for AMD64
```
I run a build against of Ubuntu Server 20.04 and it works for me:
![image](https://user-images.githubusercontent.com/47745270/183640508-89558b03-9ab4-4c8c-bc3f-69fa6584c364.png)


https://sourceware.org/pipermail/libc-alpha/2021-August/129718.html

The [release notes](https://sourceware.org/pipermail/libc-alpha/2021-August/129718.html), libdl.so no longer exists, starting from version 2.34:

> ...all functionality formerly implemented in the libraries libpthread, libdl, libutil, libanl has been integrated into libc. New applications do not need to link with -lpthread, -ldl, -lutil, -lanl anymore. For backwards compatibility, empty static archives libpthread.a, libdl.a, libutil.a, libanl.a are provided, so that the linker options keep working. Applications which have been linked against glibc 2.33 or earlier continue to load the corresponding shared objects (which are now empty).

Looks like the problem at the line - https://github.com/cake-build/cake/blob/c3f74155e88388b2354a5359a0fdde5fa5362ceb/src/Cake.Core/Polyfill/AssemblyHelper.cs#L74

```
Verifying assembly 'Cake.Sonar, Version=1.1.29.0, Culture=neutral, PublicKeyToken=null'.
Error: System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl: cannot open shared object file: No such file or directory
   at Cake.Core.Polyfill.AssemblyHelper.LoadUnixLibrary(String path, Int32 flags)
   at Cake.Core.Polyfill.AssemblyHelper.LoadAssembly(ICakeEnvironment environment, IFileSystem fileSystem, FilePath path) in C:\projects\cake\src\Cake.Core\Polyfill\AssemblyHelper.cs:line 54

```

**Comment by al-cheb** [comment]
@devlead, @patriksvensson, hey, folks. Could you please help with this issue on Ubuntu Server 22.04?

**Comment by gep13** [comment]
Adding some other folks for visibility as well...

@Jericho @augustoproiete @nils-a @ecampidoglio @daveaglick @agc93 @pascalberger @bjorkstromm

**Comment by devlead** [comment]
Raised an issue in Cake repo to track in right place
https://github.com/cake-build/cake/issues/3931

**Comment by al-cheb** [comment]
I am planning to close the thread as external. Feel free to open it if you have any concerns.

**Comment by dspeed-quantium** [comment]
Hello, I am experiencing this issue as of today with the change to `ubuntu-latest` referring to `22.04`. We do not use Cake, is there a workaround to this using 22.04? It would be my preference to use the latest rather than being stuck at v20.04.

**Comment by dmitry-kosar** [comment]
Hi! I'm having the same issue as well in the case of using MongoDB client-side encryption. 
```
System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl: cannot open shared object file: No such file or directory
   at MongoDB.Libmongocrypt.LibraryLoader.LinuxLibrary.dlopen(String filename, Int32 flags)
   at MongoDB.Libmongocrypt.LibraryLoader.LinuxLibrary..ctor(String path)
   at MongoDB.Libmongocrypt.LibraryLoader..ctor()
   at MongoDB.Libmongocrypt.Library.<>c.<.cctor>b__0_63()
```

**Comment by sathyajithps** [comment]
I'm having the same issue on .NET Core Runtime `mcr.microsoft.com/dotnet/aspnet:7.0-bookworm-slim` image which is based on Debian 12. Is there any solution to this ?

I'm also having issues on the MongoDB CSFLE encryption (libmongocrypt) package.

`Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/app/runtimes/linux/native/libdl.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.11/libdl.so: cannot open shared object file: No such file or directory
/app/libdl.so: cannot open shared object file: No such file or directory
/app/runtimes/linux/native/liblibdl.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.11/liblibdl.so: cannot open shared object file: No such file or directory
/app/liblibdl.so: cannot open shared object file: No such file or directory
/app/runtimes/linux/native/libdl: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.11/libdl: cannot open shared object file: No such file or directory
/app/libdl: cannot open shared object file: No such file or directory
/app/runtimes/linux/native/liblibdl: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.11/liblibdl: cannot open shared object file: No such file or directory
/app/liblibdl: cannot open shared object file: No such file or directory

   at MongoDB.Libmongocrypt.LibraryLoader.LinuxLibrary.dlopen(String filename, Int32 flags)
   at MongoDB.Libmongocrypt.LibraryLoader.LinuxLibrary..ctor(String path)
   at MongoDB.Libmongocrypt.LibraryLoader..ctor()
   at MongoDB.Libmongocrypt.Library.<>c.<.cctor>b__0_65()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at MongoDB.Libmongocrypt.Library.<>c.<.cctor>b__0_1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at MongoDB.Libmongocrypt.Library.get_mongocrypt_new()
   at MongoDB.Libmongocrypt.CryptClientFactory.Create(CryptOptions options)
   at MongoDB.Driver.Core.Clusters.CryptClientCreator.CreateCryptClient(CryptOptions options)
   at MongoDB.Driver.Core.Clusters.CryptClientCreator.CreateCryptClient(CryptClientSettings cryptClientSettings)
   at MongoDB.Driver.Encryption.ClientEncryption..ctor(ClientEncryptionOptions clientEncryptionOptions)`

**Comment by Vasistan** [comment]
Is this resolved? I am also facing the same issue. I am using the mcr.microsoft.com/dotnet/aspnet:6.0 image as base for mongodb CSFLE implementation

**Comment by sathyajithps** [comment]
No, we ended up using bullseye-slim instead of bookworm-slim. bullseye-slim should be the default tag on .net 7 image. Check [ASP.NET Docker](https://hub.docker.com/_/microsoft-dotnet-aspnet/).
