### ISSUE TITLE
Please consider adding `-oldest` YAML labels for older images

### ISSUE THREAD

**Issue by dundargoc** [actions/runner-images#6354]
### Feature Request

Hello! I was wondering if we could have `-oldest` YAML labels similar to the `-latest` (e.g. `ubuntu-latest`)? We like to test both versions of a system to cover as broad as range as possible, but as far as I know there's no way to point to the oldest, non-deprecated version without explicitly specifying the version. This leads to us requiring to manually bump the version in our CI (which isn't a big deal), but more importantly, it requires us to keep track of the date when an image is being deprecated and ensure we bump it before the brownout period. We would be immensely grateful if this was implemented :).

**Comment by mikhailkoliada** [comment]
CC @samvantran @Steve-Glass for possible audit and discussion

**Comment by samvantran** [comment]
Hi @dundargoc,

Thanks for your request - as of now of we don't have plans to support this. Internally we had discussed similar ideas in the past (e.g. `macos-deprecated`) but ultimately decided against it. 

Rather than adding in additional label support we've been discussing alternative options to bring more awareness to image deprecation. Things like banners at the top of the workflow runs and actions pages and more advanced warning via multiple channels (email, twitter, blog post). Ultimately, our goal is not to have to do brownouts at all.

That said, we aren't in a place yet to change the current system so I do want to remind you of the upcoming scheduled brownouts for:
- [Ubuntu 18](https://github.com/actions/runner-images/issues/6002) and
- [Macos 10.15](https://github.com/actions/runner-images/issues/5583)

**Comment by dundargoc** [comment]
I understand. Thank you for taking the time to consider it and for you work overall :).

**Comment by jamessan** [comment]
Just for clarity, the deprecation notification isn't really the issue.  We want to always build on the oldest supported runner, so that the appimage we produce has the broadest compatibility for systems it will run on.
