### ISSUE TITLE
macos-latest lacking localhost

### ISSUE THREAD

**Issue by bje-** [actions/runner-images#6383]
### Description

The macos-latest runner was failing on some Python tests I had written that made use of a simple TCP client and server. To confirm my suspicions, I added a `host localhost` command to one of my install dependencies step and sure enough I got:

    Host localhost not found: 3(NXDOMAIN)

Why doesn't the runner have an `/etc/hosts` or similar entry for `localhost`?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Image: macos-11
Version: 20221002.2
```

### Is it regression?

Unsure

### Expected behavior

I expect `localhost` to be defined as it is on ubuntu-latest.

### Actual behavior

`localhost` is not found, so tests that refer to this hostname fail.

### Repro steps

Create a build script that runs `host localhost` to reproduce.

**Comment by al-cheb** [comment]
Hey @bje-.
This is by design. The host command uses standard C library calls to contact the DNS resolvers directory; it does not use mDNSResponder or DirectoryService(bypass the system name resolver, and query DNS directly, it won't resolve names defined in /etc/hosts (unless they're also defined in the DNS service)).

To resolve ip address for host entry in /etc/hosts, you should use `dscacheutil -q host -a name localhost` command:
![image](https://user-images.githubusercontent.com/47745270/194958995-a8ab1b38-833b-4e32-a0b6-e34ab3f68faf.png)

The default DNS on macOS is set to 8.8.8.8 without localhost defined entries in it. But for test purposes you could use - 9.9.9.9:

```
 - run: host localhost || true
 - run: sudo networksetup -setdnsservers Ethernet 9.9.9.9
 - run: host localhost
```

![image](https://user-images.githubusercontent.com/47745270/194959228-5d4de5ac-3dbc-45a8-8bf1-8a0f3c4b37b6.png)

**Comment by bje-** [comment]
OK, my choice of using `host` to demonstrate the problem was not the greatest idea. I'm simply trying to illustrate that `localhost` is not a recognised hostname for applications being tested on the macos-latest runner. It doesn't strike me as unusual to expect it to be.

I'll use your workaround for now. Thanks.

**Comment by lastmjs** [comment]
Can we get this issue fixed? It seems strange that localhost simply doesn't work on MacOS. I have test code that is identical running on Ubuntu runners, and switching to MacOS runners are tests simply started failing in a very confusing way.
