### ISSUE TITLE
Chrome and chromedriver aren't identical 

### ISSUE THREAD

**Issue by AlexeyCL** [actions/runner-images#6489]
### Description

Sometimes chrome and chromedriver aren't identical. I think in this case, you shouldn't update chrome. Based on [PR](https://github.com/actions/runner-images/pull/6330)
Today we have chrome version 106, but driver 107 and they can't work together 

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

latest version of ubuntu

### Is it regression?

no

### Expected behavior

chrome driver and chrome should be same version

### Actual behavior

chrome driver and chrome have different versions

### Repro steps

1. clone repo
2. look into versions

**Comment by erik-bershel** [comment]
@AlexeyCL 
Hi! All three versions of Ubuntu runner images have same major versions of the Chrome browser and Chrome driver, just due to the #6330.
[Ubuntu 18.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu1804-Readme.md#browsers-and-drivers), [Ubuntu 20.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#browsers-and-drivers), [Ubuntu 22.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#browsers-and-drivers).
And results of test for Ubuntu 20.04 runner:
<img width="1015" alt="Снимок экрана 2022-10-30 в 22 20 49" src="https://user-images.githubusercontent.com/110455084/198902138-a736f05c-7fba-40da-8d56-213f845123a9.png">

I suspect that a driver or browser is being updated in your pipeline. Due to the absence of a problem, I am forced to close the issue.
