### ISSUE TITLE
Add Serverless tool to ubuntu image

### ISSUE THREAD

**Issue by user-muthu** [actions/runner-images#6554]
### Tool name

serverless

### Tool license

open source

### Add or update?

- [X] Add
- [ ] Update

### Desired version

whatever is latest

### Brief description of tool

To use aws serverless deployments we need serverless tool to be used in images inside Github actions.

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by al-cheb** [comment]
Hey @user-muthu.
We are not going to add serverless due to lack of free space on images and maintenance concerns.

Install in runtime:
```
      - run: |
          curl -LO https://github.com/serverless/serverless/releases/latest/download/serverless-linux-x64
          chmod +x ./serverless-linux-x64
          sudo mv ./serverless-linux-x64 /usr/local/bin/
      - run:
          serverless-linux-x64 --version
```
![image](https://user-images.githubusercontent.com/47745270/201390825-46854488-b6ad-4b3f-8997-29e1fa60e73c.png)

or use Github Action for Serverless task - https://github.com/marketplace/actions/serverless
