### ISSUE TITLE
.net core SDK 6.0.402 no longer on latest image

### ISSUE THREAD

**Issue by HenrikSommer-eng** [actions/runner-images#6577]
### Description

Our build are failing because .net core skd 6.0.402 are longer on all Windows Server 2022 image.

Error message when restoring:
```
Requested SDK version: 6.0.402
global.json file: D:\a\1\s\global.json

Installed SDKs:

Install the [6.0.402] .NET SDK or update [D:\a\1\s\global.json] to match an installed SDK.
3.1.120 [C:\Program Files\dotnet\sdk]
3.1.202 [C:\Program Files\dotnet\sdk]
3.1.302 [C:\Program Files\dotnet\sdk]
3.1.425 [C:\Program Files\dotnet\sdk]
5.0.104 [C:\Program Files\dotnet\sdk]
5.0.214 [C:\Program Files\dotnet\sdk]
5.0.303 [C:\Program Files\dotnet\sdk]
5.0.408 [C:\Program Files\dotnet\sdk]
7.0.100 [C:\Program Files\dotnet\sdk]
```

Image say that 6.0.402 should still be on the image:
https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#net-core-sdk

"orchestrationPlan":{"planId":"58f53f58-f301-4a5d-827d-a60c6599a929"}

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

2022-11-16T07:34:54.5000499Z Agent name: 'Hosted Agent'
2022-11-16T07:34:54.5000998Z Agent machine name: 'WIN-18M6RGO71EN'
2022-11-16T07:34:54.5001236Z Current agent version: '2.213.2'
2022-11-16T07:34:54.5049746Z ##[group]Operating System
2022-11-16T07:34:54.5050074Z Microsoft Windows Server 2022
2022-11-16T07:34:54.5050263Z 10.0.20348
2022-11-16T07:34:54.5050424Z Datacenter
2022-11-16T07:34:54.5050581Z ##[endgroup]
2022-11-16T07:34:54.5050754Z ##[group]Runner Image
2022-11-16T07:34:54.5050947Z Image: windows-2022
2022-11-16T07:34:54.5051134Z Version: 20221111.1

### Is it regression?

.

### Expected behavior

.net core sdk 6 version is installed on image

### Actual behavior

.net core sdk 6 is not installed on image (some image)

### Repro steps

1. run a pipeline that require .net core 6 sdk.

**Comment by HenrikSommer-eng** [comment]
Some more orchestrationPlan id it helps you:
"orchestrationPlan":{"planId":"96272998-292c-4c25-9c5f-df2a8648e3a9"}
"orchestrationPlan":{"planId":"108f027b-35dd-4a69-aa34-e6c72d04d1f4"}
"orchestrationPlan":{"planId":"e42ddf5f-4ed9-4727-8dc1-0f5c8d795191"}
"orchestrationPlan":{"planId":"ebca9e3d-7ff8-473b-a342-6bf280d7528e"}

**Comment by vedion** [comment]
I looks like it is on purpose on the new pre-release:
https://github.com/actions/runner-images/releases/tag/win22%2F20221111.1

Please fix microsoft.

**Comment by mkriventsev** [comment]
Regarding the readme you referred to, there is a PR opened already to remove .NET 6 from it to be aligned with the current image configuration:
https://github.com/actions/runner-images/pull/6567/files#diff-a1f67f5c4a583bf90c239743379ad9473fbf1fa9d11c5cb7739c8012404dcc7aR541

.NET 6 is LTS, and looks like, according to the Software and Image Support Policy https://github.com/actions/runner-images/blob/main/README.md#software-and-image-support there should be two latest LTS versions supported, so including .net 6. Or am I missing something?
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core#lifecycle

Our pipelines failed with windows-latest as well, because of the removed .net 6 SDK, so we were forced to install .NET 6 SDK explicitly.

**Comment by drk-mtr** [comment]
The `windows-2022` image has a load of dotnet 5 versions and dotnet 7, but not dotnet 6 LTS. If this is a deliberate decision it's a very strange one.

All our builds pipelines failed yesterday, and today all of our builds are taking longer because of the extra `UseDotNot@2` install task. Thankfully I knew the fix, because this has happened before. Trying to use global.json files in a CI/CD environment where MS keep messing around with what's on the box is a minefield, very painful.

**Comment by erik-bershel** [comment]
@HenrikSommer-eng @vedion @mkriventsev @drk-mtr 
We'll fix issue as soon as possible.

**Comment by mattjohnsonpint** [comment]
.NET 5 needs to be removed.  It's not LTS, and not current.  See also:
https://github.com/actions/runner-images/issues/6539#issuecomment-1309276738

**Comment by KrylixZA** [comment]
For whatever reason, using `dotnet restore` rather than `nuget.exe restore` in the pipeline appears to work. It uses the .NET 7 SDK to do the restore and build, which seems to have backward compatibility to do the builds. I am not sure it is by design, but it is a workaround for this problem in the interim.

**Comment by HenrikSommer-eng** [comment]
@KrylixZA `dotnet restore` use latest version if you dont have a `global.json` file it will use the specificer version and fail if it is not installed.

**Comment by KrylixZA** [comment]
@HenrikSommer-eng that makes complete sense. Thanks for clearing that up!

**Comment by mikhailkoliada** [comment]
We restored the old image due to powershell 7.3 breaking changes, new release will include dotnet 6.x on windows in any way.

**Comment by duaneking** [comment]
Now getting "Error NETSDK1045: The current .NET SDK does not support targeting .NET 7.0. "

Please have somebody on this team add a unit test or something to track and make sure that version six and seven are actually added to the image every time.

**Comment by vpolikarpov-akvelon** [comment]
Hey @duaneking. Please create a separate issue and provide more details if there is a problem still.
