### ISSUE TITLE
Breaking change in PowerShell 7.3 PSNativeCommandArgumentPassing 

### ISSUE THREAD

**Issue by mikeharder** [actions/runner-images#6586]
### Description

PowerShell 7.3 includes a change that may break scripts and automation:

https://learn.microsoft.com/en-us/powershell/scripting/learn/experimental-features?view=powershell-7.3#psnativecommandargumentpassing

Some of our scripts were breaking today when running on agents with PowerShell 7.3.

Perhaps the images should set `$PSNativeCommandArgumentPassing = "Legacy"` by default?

Otherwise I think upgrading the images to PowerShell 7.3 is going to break a lot of scripts.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20221111.1

### Is it regression?

Yes, from 20221027.1

### Expected behavior

Existing PowerShell scripts should not be broken

### Actual behavior

Existing PowerShell scripts may be broken, since the default value of `$PSNativeCommandArgumentPassing` is changed in PowerShell 7.3

### Repro steps

The examples under https://learn.microsoft.com/en-us/powershell/scripting/learn/experimental-features?view=powershell-7.3#psnativecommandargumentpassing should be sufficient to repro this.

**Comment by erik-bershel** [comment]
Hello @mikeharder 
We are already working on the issue. To temporarily stop the problem, we will return the previous versions of the images to work. We will report on the following decisions separately. And thank you for the information about setting $PSNativeCommandArgumentPassing = "Legacy". It is useful.

**Comment by mikhailkoliada** [comment]
Powershell were downgraded to 7.2

**Comment by kilasuit** [comment]
As I mentioned in [this comment](https://github.com/Azure/azure-powershell/issues/18721#issuecomment-1317804687) the right fix overall would be to get this [feature request](https://github.com/microsoft/azure-pipelines-tasks/issues/17219) pushed through

**Comment by mikeharder** [comment]
@kilasuit: Thanks for the suggestion, but that feature request is not related to this issue.  This issue is a breaking change in PowerShell 7.3 argument passing that can impact any PowerShell script.  It is not related to AzurePowerShell.

**Comment by kilasuit** [comment]
@mikeharder I still think that it is semi-related as it would be beneficial if within your images you were to allow version pinning of the available tooling like PowerShell (not just for AzurePowerShell) or node or anything else that may be needed. because that would stop issues like this from happening in future. Not saying that it is an easy fix but it would give more confidence in not accidentality breaking existing running processes in future. Will you look into doing this, I don't know, but I'd feel wrong if I hadn't at least made the recommendation for you/team to at least ponder over. What happens from there is obviously up to you/team to decide.

**Comment by Holger1968** [comment]
Is this fixed in v7.3.1?
