### ISSUE TITLE
Update/Add lz4 (Missing in new version)

### ISSUE THREAD

**Issue by acuD1** [actions/runner-images#6713]
### Tool name

lz4

### Tool license

https://github.com/lz4/lz4/blob/dev/LICENSE

### Add or update?

- [ ] Add
- [X] Update

### Desired version

Latest

### Brief description of tool

Hello, the binary lz4 is missing on the new `ubuntu-22.04` image, version `20221127.1`.

Regards.

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
apt-get install lz4
```

**Comment by erik-bershel** [comment]
Hi @acuD1!
I checked our scripts. We not installing that package directly. So if it existed somewhere in our images previously so that is the direct result of dependencies of other software.
In result I want say that we won't add that package directly because you may install it in runtime in less than 12 seconds without any maintenance concerns.

**Comment by mikhailkoliada** [comment]
@erik-bershel we should add it as it is pretty much basic package

**Comment by erik-bershel** [comment]
@acuD1 changing the plan. I'll add that package soon.

**Comment by mikhailkoliada** [comment]
Will be deployed next week

**Comment by mikhailkoliada** [comment]
Deployed
