### ISSUE TITLE
add xmlstarlet tool in ubuntu runners

### ISSUE THREAD

**Issue by nisho06** [actions/runner-images#6728]
### Tool name

xmlstarlet

### Tool license

MIT License

### Add or update?

- [X] Add
- [ ] Update

### Desired version

whatever is latest

### Brief description of tool

XMLStarlet is a set of command line utilities (toolkit) to query, transform, validate, and edit XML documents and files using a simple set of shell commands in a way similar to how it is done with UNIX grep, sed, awk, diff, patch, join, etc commands.

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by erik-bershel** [comment]
Hello @nisho06!
Thank you for request. But we trying to avoid installing additional packages to our images because of maintenance concerns. That particular package you may install in runtime in about 10 seconds and there are a lot of similar tools for Ubuntu like xml-twig-tools.
Example of install:
<img width="1041" alt="Снимок экрана 2022-12-09 в 09 33 58" src="https://user-images.githubusercontent.com/110455084/206659574-54616b72-334f-4bf8-b0e3-32b3722d838a.png">
If you have any questions or concerns, you can open a new issue or ping me here.
