### ISSUE TITLE
[All OSs] .NET 5.x will be removed from the images on February, 6

### ISSUE THREAD

**Issue by mikhailkoliada** [actions/runner-images#6840]
### Breaking changes

All the pre-cached .NET 5.x versions will be removed from all operating systems.

### Target date

The rollout will start on February, 6 and will take 3-4 days to propagate the image to all the environments.

### The motivation for the changes

 According to our [Software and image guidelines](https://github.com/actions/runner-images#software-and-image-support) tools and versions have to be removed 6 months after they are deprecated or have reached end-of-life. The .NET 5 [has reached EOL on 5 May 2022](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core).

### Possible impact

If your project depends on a pre-installed .NET 5.x it can be broken.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Mitigation ways

To install any version in runtime you can use the following action\task:

* https://github.com/actions/setup-dotnet for GH actions
* https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops task for AzDO

**Comment by Hsaameett57** [comment]
Access

**Comment by mikhailkoliada** [comment]
Removed. Changes will be released next week.

**Comment by mikhailkoliada** [comment]
Deleted

**Comment by blairconrad** [comment]
Not entirely on topic, but what is the best way for consumers of these images to become aware of impending removals like this?
Following this repo and sorting through all the issues doesn't really appeal. Otherwise should we note down the EOL dates for the software we care about, add 6 months and create calendar entries for ourselves? I looked for a way to subscribe to an issue label, or to get an RSS feed for issues tagged with a label, and came up short.

Thanks.
