### ISSUE TITLE
Pipelines fail for `windows-latest` but not `ubuntu-latest`

### ISSUE THREAD

**Issue by Marvin-Brouwer** [actions/runner-images#6841]
### Description

Hi,

I've been playing around with matrices in the hopes of increasing my pipeline speed.
That worked. However, since I've added `windows-latest` as a matrix configuration, I'm getting errors like the following on the windows image.
```txt
The operation was canceled.
```
```txt
An error occurred while provisioning resources (Error Type: Disconnect).
```
```txt
The hosted runner: GitHub Actions 16 lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
```
So I put the `max-parallel` property to 1 to see what happens then.
It appears that only the `windows-latest` jobs are failing, but which of the other matrix parameters doesn't matter. Making me believe it might be a runner specific problem:

> [Benchmark XML serializer / netcoreapp3.1 windows](https://github.com/Marvin-Brouwer/FluentSerializer/actions/runs/3781208566/jobs/6427921535#logs)
```txt
Received request to deprovision: The request was cancelled by the remote provider.
```

> [Benchmark XML serializer / net7.0 windows](https://github.com/Marvin-Brouwer/FluentSerializer/actions/runs/3783668330/jobs/6432579707#logs)
```txt
Process completed with exit code -532462766.
```

Additionally, I'm running profilers on multiple libraries and only the XML benchmarks seem to have this issue.

---

Of course I did google a bit, and it doesn't seem like any of my jobs is over the limit for free open source repositories, it always fails within 2 hours.

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Version: GitHub hosted runnder `windows-latest`
Build link: https://github.com/Marvin-Brouwer/FluentSerializer/actions/runs/3781208566

### Is it regression?

No

### Expected behavior

The expected behavior would be for the job to run to completion.

### Actual behavior

One of the windows benchmark jobs gets cancelled seemingly random.

### Repro steps

Rerun https://github.com/Marvin-Brouwer/FluentSerializer/actions/runs/3781208566 pipeline.

**Comment by erik-bershel** [comment]
Hey @Marvin-Brouwer, we'll take a look soon. On first sight it looks like your benchmark task bothering resources limitations but I should check it.

**Comment by Marvin-Brouwer** [comment]
Hey @erik-bershel,

I'm kind of expecting that also, I just don't know what it's maxing out and how to inspect that.
I don't want to get ahead of ourselves. But if that's the case, maybe it helps to state that explicitly in the cancellation warning?

**Comment by mikhailkoliada** [comment]
Just marking as a dup of #6709 as they are of the same origin I guess.

**Comment by Marvin-Brouwer** [comment]
@mikhailkoliada I'm not sure they are tbh.
I see #6709 is failing on Ubuntu runners, while mine are only failing on Windows runners.
They may be similar of origin, but isn't it too early to know?

**Comment by Marvin-Brouwer** [comment]
Some additional context:

I played around a bit and ran it once in `32bit`.
Obviously it ran out of memory if the `64bit` is already struggling, however what's interesting is that I now get a clear message: https://github.com/Marvin-Brouwer/FluentSerializer/actions/runs/3910112429/jobs/6682306899.
```txt
Unhandled Exception: OutOfMemoryException.
```

Maybe it's related, maybe it's not. But, at least this is what I'm expecting to see when I'm overloading the system. Not a canceled pipeline without any log output.

**Comment by Marvin-Brouwer** [comment]
Another bit of context.
I decreased the dataset for benchmarking and now the pipelines run to completion.
So it's very likely a memory issue.

**Comment by fragsman** [comment]
I've been struggling for 2 days. The same message "something in your workflow terminates..." INCORRECT. 

My GH runner was refusing to finish the job. A Selenium Suite that I've developed and worked with GH Actions since 2022. With about 15 tests which finishes under 2 minutes always. I've made several enhancements and even tested different branches disabling logs, disabling tests, etc. None seemed to work. 

I changed from **windows-latest** to **windows-2022**. It worked inmediately.

I know I get this for free but how come the issue is on Github Runners and there is no way to reset them or get a proper message? I mean. windows-latest always worked and suddenly it doesn't work anymore.

**Comment by erik-bershel** [comment]
Hey @fragsman!

I'm not sure if your case is related to the problem that was originally discussed in this issue. If you still encounter this unpleasant behavior, please open a new issue with all the required information - we will definitely try to help you.

**Comment by fragsman** [comment]
Hi @erik-bershel . I've been working in a repo just for "fun/study". The workflow has been failing a LOT. I said above it worked with windows-2022 but it was temporary. Next run it failed. I had another repo with very similar configs and everything. Is not failing at all.

I conclude is a GitHub problem since I saw it passing with no-significant changes and then failing for no reason. It's all public.

https://github.com/fragsman/auto-framework (Actions failing for no apparent reason)
https://github.com/fragsman/bdd-framework (Actions working properly)

Ps. It never ever hands or whatsoever locally. It is just GH. I even disabled actions to try to reset somehow the Virtual Machines and then re-configuring again deleting the old Actions history but no luck.
