### ISSUE TITLE
Can't get correct .coverage report file with win22/20221204.3 

### ISSUE THREAD

**Issue by Darwin-Li-001** [actions/runner-images#6848]
### Description

Do unit test with "windows-2022" in Azure pipeline. 
![image](https://user-images.githubusercontent.com/57886721/209898402-812aed8c-51db-476d-80ce-fa59813fcef6.png)

The result was always correct before, but since the agent upgrade to version 20221204.3, we can't get Unit Test coverage correctly.
And the size of  **.coverage** file is not as big as normal.
please help to have a debug. Thanks!

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

pool:
          vmImage: "windows-2022"    ->"20221204.3 "

### Is it regression?

No

### Expected behavior

correct *.coverage file should be got.

### Actual behavior

The *.coverage file is to small.
![image](https://user-images.githubusercontent.com/57886721/209898910-238b6b01-ca14-4e97-a166-b6717c59f223.png)

### Repro steps

1.Run unit test with VS test in Azure pipeline;
2.Try to get the unit test coverage.

**Comment by erik-bershel** [comment]
Hey @Darwin-Li-001, we'll try to help you with this.

**Comment by Darwin-Li-001** [comment]
> 

Thanks @erik-bershel , that's so kind of you!
Any update please let me know. Thanks again!

**Comment by Alexey-Ayupov** [comment]
Hello @Darwin-Li-001, I have tried to reproduce the issue and I can get this coverage file through publish artifact task however, I cannot open it to check if it is valid or not. 
Satring from 20221204.3 version Visual Studion and its components were updated several times. We cannot downgrade it, and it seems like we cannot do much about it.
Since you are using "VSTest@2 - Visual Studio Test v2 task" you can log the issue to https://github.com/microsoft/vstest in order to continue investigation.

If you have any questions, feel free to reach us.
