### ISSUE TITLE
Ubuntu 2204 build doesn't become Azure Image

### ISSUE THREAD

**Issue by agentq15** [actions/runner-images#6914]
### Description

We have no issue building Ubuntu 2004 image.
But now when we changed to Ubuntu 2204 the build works fine but no Image ends up in the resource group.
I can see a vhd file inside the storage account but it is not converted to an Image
![image](https://user-images.githubusercontent.com/10948042/212348175-aa35c191-419c-492b-b0af-9a357a875774.png)

What am I doing wrong?

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current agent version: '2.214.1'

### Is it regression?

No

### Expected behavior

We will get an Azure Image inside the resource group
Previous build log ended with this message which the new one doesn't
![image](https://user-images.githubusercontent.com/10948042/212349554-01ddd628-e2aa-486b-b23c-9c499bc070c1.png)

### Actual behavior

Build is working but just ends up as a VHD file inside the storage account
![image](https://user-images.githubusercontent.com/10948042/212349214-010027bd-2f5e-4b33-a6c7-db875381ff82.png)

### Repro steps

Run build pipeline

**Comment by mikhailkoliada** [comment]
hello, which way are you building (which script are you running) exactly to build the image?

**Comment by agentq15** [comment]
> hello, which way are you building (which script are you running) exactly to build the image?

We just run this one 
https://github.com/actions/runner-images/blob/main/images.CI/linux-and-win/azure-pipelines/ubuntu2204.yml

Before we ran this one and it still works
https://github.com/actions/runner-images/blob/main/images.CI/linux-and-win/azure-pipelines/ubuntu2004.yml

They both use the same template and it is just the image_type that changes.

**Comment by erik-bershel** [comment]
Hey @agentq15!
Please take a look on that part of our [guide](https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md#generated-vm-deployment). 
I suppose here you missing moment with difference betwen image generation that just generate vhd and json files and real VM creation that described in guide. Maybe previously you used selfwriten pipeline or script which contain both those generation and deploying steps.

**Comment by erik-bershel** [comment]
@agentq15 you can use that [helper function](https://github.com/actions/runner-images/blob/main/helpers/GenerateResourcesAndImage.ps1) to prepare Azure Image. Our CI pipelines you have mentioned [here](https://github.com/actions/runner-images/issues/6914#issuecomment-1383595997) never prepared Image but only VHDs.
Please, check what code you really used for creating Ubuntu20 because screenshot you posted doesn't looks like a result of our base [pipeline](https://github.com/actions/runner-images/blob/main/images.CI/linux-and-win/azure-pipelines/image-generation.yml).

**Comment by agentq15** [comment]
Found what we had changed in the other config.

Need to add this 

> variable "managed_image_resource_group_name" {
  type    = string
  default = "${env("MANAGED_IMAGE_RESOURCE_GROUP_NAME")}"
}
variable "managed_image_name" {
  type    = string
  default = "${env("MANAGED_IMAGE_NAME")}"
}

And add this under build_vhd
> managed_image_resource_group_name      = "${var.managed_image_resource_group_name}"
  managed_image_name                     = "${var.managed_image_name}"
  
  And remove this:
  > capture_container_name                 = "images"
  capture_name_prefix                    = "${var.capture_name_prefix}"
  resource_group_name                    = "${var.resource_group}"
  storage_account                        = "${var.storage_account}"
  
  Started getting this now instead 
`  /imagegeneration/SoftwareReport/SoftwareReport.Generator.ps1 : Exception setting "Version": "The argument is null or empty. Provide an argument that is not null or empty, and then try the command again."`
Any ideas on why?

**Comment by erik-bershel** [comment]
Hi @agentq15,
You got that error message because you didn't update your fork. Issue you mentioned covered by that [PR](https://github.com/actions/runner-images/pull/6919) merged. More info here: https://github.com/actions/runner-images/issues/6922

I'll close that issue because it isn't connected with any current issues. Feel free to ping me here if you have another questions about topic. Or you may open issue in case you have new concerns.

**Comment by agentq15** [comment]
Perfect, thank you!
