### ISSUE TITLE
no exit code if OnError=abort when image generation failed

### ISSUE THREAD

**Issue by alex-3sr** [actions/runner-images#7108]
### Description

Hi everyone,

Recent update permit to set OnError when packer failed. I notice that when it failed with abort parameters, the Azure DevOps task is show as completed and not failed.
So I'm unable to set a retryCountOnTaskFailure for autoamtic retry, and then next task will failed cause need the image.

Are there any way to set and error exit code when we set OnError=abort when it failed ?

Thanks and have a nice day
Regards
Alexandre

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

I've same issue on Windows and Linux image, not linked to a specific version, but on Packer command

### Is it regression?

No

### Expected behavior

When image generation failed, the devops task need to be failed too

### Actual behavior

If image generation failed, the devops task is shown as completed

### Repro steps

Setup an Azure Devops pipeline and using paramter OnError=abort, and when image generation failed, the task will be show as "complted" and not "failed"

**Comment by erik-bershel** [comment]
Hey @alex-3sr!
Option you have mentioned is not connected with whole script execution. It is packer build on-error option only. Take a look [here](https://developer.hashicorp.com/packer/docs/commands/build#on-error-cleanup) please. And a source code [here](https://github.com/actions/runner-images/blob/main/helpers/GenerateResourcesAndImage.ps1#:~:text=packerBinary%20build%20%2D-,on%2Derror,-%3D%22%24).
When packer build was failed it is not an end for a script work by design for that helper.

**Comment by alex-3sr** [comment]
> Hey @alex-3sr! Option you have mentioned is not connected with whole script execution. It is packer build on-error option only. Take a look [here](https://developer.hashicorp.com/packer/docs/commands/build#on-error-cleanup) please. And a source code [here](https://github.com/actions/runner-images/blob/main/helpers/GenerateResourcesAndImage.ps1#:~:text=packerBinary%20build%20%2D-,on%2Derror,-%3D%22%24). When packer build was failed it is not an end for a script work by design for that helper.

Hi,

Thank you for your response. I take a look on packer command, and don't see argumets for manipulate exit code. So do you mean that I've to check exit code after packer build command (like with $LASTEXITCODE) and then set a trhow or similar for catch it and break the DevOps task ?

If yes, I can start a fork and propose a PR

Regards
Alex

**Comment by erik-bershel** [comment]
Hi @alex-3sr,
You may propose some changes but not connected with that "on-fail" option. That one is for packer build only and describes a bit else part of action. If you want to get exit code you can break current try-catch logic of helper or you can do it the way you mentioned with additional "exit code checker" outside of main try-catch. But I'm not sure we'll accept any of this changes because those may break another users automation.
