### ISSUE TITLE
Update Clang/LLVM

### ISSUE THREAD

**Issue by ZotyDev** [actions/runner-images#7302]
### Tool name

Clang/LLVM

### Tool license

Apache-2.0 WITH LLVM-exception

### Add or update?

- [ ] Add
- [X] Update

### Desired version

15.0.7

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by erik-bershel** [comment]
Hey @ZotyDev! 
Clang-14 is the latest version of package provided via official canonical repo for APT in jammy (Ubuntu 22.04) list. [Link](https://packages.ubuntu.com/search?keywords=clang&searchon=names&suite=jammy&section=all).
We won't use build from source or download ubuntu-18 prebuilded binaries method due to maintenance concerns, so I have to close that issue.
