### ISSUE TITLE
Add Windows ARM64 support

### ISSUE THREAD

**Issue by Colengms** [actions/runner-images#7507]
### Tool name

Windows-ARM64

### Tool license

Microsoft

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

Opening this again as https://github.com/actions/runner-images/issues/6532 has been duped to itself. (?)  If there is already an issue for this (that is still open), please dupe to that.  Or, if this is already supported somehow, please respond with a reference to instructions.)

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by erik-bershel** [comment]
Clone for: https://github.com/actions/runner-images/issues/768
Nothing really changed from mentioned issue times.

**Comment by alshdavid** [comment]
Microsoft are releasing the arm64 powered Surface laptops next month so I'd like to start offering Windows arm64 binaries for my FOSS project.

Currently I am manually building binaries on a MBP and adding them to my GH auto-generated releases.

I'm exploring setting up a self hosted runner on my homelab PC (an old x86_64 machine I have at home) via QEMU and CPU emulation. Another option I've considered is buying a dedicated SBC (like an RPI5, Orange Pi 5, etc), installing Windows on Arm on it and setting it up as a self hosted runner. I also looked at using an AWS arm instance (m7g) and running a Windows VM on it but they don't support virtualization.

In Australia, Microsoft's arm dev kit (Volterra) is close to $1k and there aren't any on the used market - at that price I'm better off buying a M1 Mac Mini.

That said, self hosted runners are not recommended for public repos (even for `workflow_dispatch` pipelines) because if someone forks your project they can modify the workflow and tell your self hosted runner to do stuff or spam it with pipelines. I'm not sure if there's a workaround for that.
