### ISSUE TITLE
Update/Add linux-modules-extra-azure

### ISSUE THREAD

**Issue by DaanDeMeyer** [actions/runner-images#7570]
### Tool name

linux-modules-extra-azure

### Tool license

Same license as linux-image-azure

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Same version as linux-image-azure

### Approximate size

125.93 MB

### Brief description of tool

This package contains extra kernel modules for the linux-image-azure kernel package that the runner images are using. We're looking to mount erofs filesystems for [systemd](https://github.com/systemd/systemd) integration tests which need the erofs kernel module which is available from linux-modules-extra-azure.

We need this to be installed in the regular image because the version of the modules needs to match the version of the running kernel, otherwise the modules can't be loaded by the running kernel. We can't install the version that matches the running kernel because newer versions get released and older versions of the package are removed from the Ubuntu repositories.

Another option is to make sure that a version of the linux-modules-extra-azure package that matches the kernel package that is shipped in the current image version is always available.

Currently, if I do `sudo apt-get install linux-modules-extra-$(uname -r)`, the command fails because the matching version is not available in the mirrors. This requires the GA team to make sure the version is available in the azure apt mirrors until the runner image with the same kernel version is no longer in use.

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
sudo apt-get install linux-modules-extra-azure
```

**Comment by sergei-pyshnoi** [comment]
Hello @DaanDeMeyer . We will take a look.

**Comment by bluca** [comment]
> Hello! We would not like to install the package due to maintenance concerns as well as lack of high demand from other customers. If you have questions left feel free to reach us again.

This is not a problem that we can solve in our GA actions in any way. The images simply get out of sync with the repositories. Please reconsider.

**Comment by bluca** [comment]
The kernel in the repository is updated, so the old modules for the kernel that is actually running in the images you make available no longer exist and cannot be installed. We are unable to run CI jobs and add coverage for security-related features due to this issue.

**Comment by bluca** [comment]
Here are some clarifications:

These kernel modules cannot lag behind the actual kernel update when you install both together, as they are all built from the same source package. Canonical choose to split it out in multiple binary packages, for some reasons. When you install the kernel image package and that extra-module package at the same time, they are guaranteed to be compatible, as the unversioned metapackages that you are referencing point to the exact same kernel build. This is guaranteed by how the packages are set up.

The problem arises because the kernel package is installed whenever the image is built, and we are trying to install the extra modules package long after that has happened, on the user script. By installing both at image creation time, they will be in sync.

You can see that linux-image-azure and linux-modules-extra-azure are part of the same source package and thus are built and published together here:

https://packages.ubuntu.com/source/jammy-updates/linux-meta-azure

And if for some weird, strange circumstance that does go out of sync at image creation time, nothing bad happens, there's simply some unusable kernel modules. The installation location is named after its ABI, so it won't affect the actual kernel.

To be extra clear: these are not out-of-tree or 3rd party kernel modules. They have been part of the mainline kernel since ages, and are all built together with the kernel image itself. It's just that Canonical choose to organize them in separate packages for some reason, built at the same time. They cannot go out of sync or be incompatible.

**Comment by bluca** [comment]
reopened at https://github.com/actions/runner-images/issues/7587
