### ISSUE TITLE
Visual Studio 2022 17.6

### ISSUE THREAD

**Issue by Sergio0694** [actions/runner-images#7612]
### Tool name

Visual Studio 2022

### Tool license

https://visualstudio.microsoft.com/license-terms/vs2022-ga-proenterprise/

### Add or update?

- [ ] Add
- [X] Update

### Desired version

17.6 (see https://devblogs.microsoft.com/visualstudio/visual-studio-2022-17-6-now-available/)

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by shamil-mubarakshin** [comment]
Hello @Sergio0694, Windows Serv 2019 doesn't have Visual studio 2022 17.6.
It will be available on Windows Server 2022 with next deployed image

**Comment by Sergio0694** [comment]
Yeah sorry I wasn't really sure about that one, just checked that box to do the same as I saw done in the past issue for VS 2022 17.4 😅
I'll remove that just to avoid confusion. Thank you!

**Comment by MartinDemberger** [comment]
My current build is corrupted and I see the message `CSC : warning CS9057: The analyzer assembly 'C:\hostedtoolcache\windows\dotnet\sdk\7.0.302\Sdks\Microsoft.NET.Sdk.Razor\source-generators\Microsoft.NET.Sdk.Razor.SourceGenerators.dll' references version '4.6.0.0' of the compiler, which is newer than the currently running version '4.5.0.0'.` I assume this is the case because of the 17.6 not being installed.

is there any possibility to upgrade the visual studio to the newest version inside my yaml pipeline or do I have to wait for this issue to be done?

**Comment by jlaanstra** [comment]
Is there an ETA for this? I was hoping to get 17.6 on the machines this week.

**Comment by shamil-mubarakshin** [comment]
@Sergio0694, @jlaanstra, @MartinDemberger apologies for the delayed notice.
Image with VS 17.6 has been deployed.
