### ISSUE TITLE
macOS 11, Xcode 12, iOS 13 simulator builds hang forever

### ISSUE THREAD

**Issue by dfed** [actions/runner-images#7687]
### Description

On Xcode 12.5 running on macOS 11, iOS 13 simulator builds hang for six hours and then time out. 

On Xcode 12.4 running on macOS 11, iOS 13 simulator builds and iOS 14 simulator builds hang for six hours and then time out. 

This is relatively new behavior – I know the Xcode 12.4 configurations used to work.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Xcode 12.5 / macOS 11 / iOS 13 simulator: https://github.com/square/Valet/actions/runs/5215139022/jobs/9412327336?pr=300

Xcode 12.4 / macOS 11 / iOS 13 simulator: https://github.com/square/Valet/actions/runs/5157870997/jobs/9290846796?pr=299
Xcode 12.4 / macOS 11 / iOS 14 simulator: https://github.com/square/Valet/actions/runs/5157870997/jobs/9290846676?pr=299

### Is it regression?

Yes. Prior successful Xcode 12.4 / macOS 11 / iOS 13 simulator: https://github.com/square/Valet/actions/runs/4548577245/jobs/8019748063 . Prior successful Xcode 12.4 / macOS 11 / iOS 14 simulator: https://github.com/square/Valet/actions/runs/4548577245/jobs/8019747967

### Expected behavior

I expect builds to succeed or fail, not hang and time out.

### Actual behavior

Build times out.

### Repro steps

Attempt to rebuild any of the above failing jobs.

**Comment by erik-bershel** [comment]
Hey @dfed!
I'll take a look

**Comment by druzm** [comment]
I think I may be experiencing a similar issue: https://github.com/gaia-dpci/GaiaXPy/actions/runs/5289393980

Both MacOS and Windows builds won't finish, and it's been happening for around a month now. The timeout used to be set to 360 minutes, but I reduced it as requested by GitHub support.

Sometimes not even a single test will run, and some others the build will end up stuck in a particular test file. I've tried removing entire test folders from the repo, but it hasn't changed anything. As tests sometimes won't run at all, I'm convinced now the problem is not in my code.

**Comment by vpolikarpov-akvelon** [comment]
Hey @dfed. Unfortunately I failed to reproduce this issue either in GitHub and in my local environment. Everything seems to work fine currently. I also tried to run you workflow on a virtual machines created using older images (2 weeks old and 4 weeks old) and didn't find anything either. Could you try running your workflows again?

**Comment by vpolikarpov-akvelon** [comment]
Glad to hear that! Feel free to reach out again if your problem return or you have other questions.
