### ISSUE TITLE
[macos]: strange error during homebrew install

### ISSUE THREAD

**Issue by igagis** [actions/runner-images#7725]
### Description

Recently I started getting strange error for my macos builds:
https://github.com/cppfw/svgdom/actions/runs/5240488083/jobs/9518560473#step:5:584

it happens during `brew install` phase and the error message is not very informative, just:
```
Error: Process completed with exit code 1.
```

Some days ago everything was working.

any idea what could be wrong?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/cppfw/svgdom/actions/runs/5240488083/jobs/9518560473#step:5:584

### Is it regression?

yes

### Expected behavior

last successful build https://github.com/cppfw/svgdom/actions/runs/5190159946/jobs/9357595638

### Actual behavior

error during `brew install`

### Repro steps

see build link

**Comment by vpolikarpov-akvelon** [comment]
Hi @igagis. We will take a look.

**Comment by vpolikarpov-akvelon** [comment]
Hey @igagis. I investigated this error and here are some info.

The event that have exposed this issue is release of Python 3.11.4 that happened on 6 June. As soon as it had released your pipeline started trying to upgrade Python 3. The error in your pipeline is here: https://github.com/cppfw/svgdom/actions/runs/5240488083/jobs/9501787549#step:5:207

Unfortunately there is a known problem with Python 3 upgrading. Some users still require Python 2 but it's absent from official Homebrew repo since 2020 so [we are installing](https://github.com/actions/runner-images/pull/2217) package served by python's team. The package installs link `/usr/local/bin/2to3` that [causes conflict](https://github.com/actions/runner-images/issues/2322) when installing or updating Python 3 afterwards.

You can see the same error in runner image build log: https://github.com/actions/runner-images/actions/runs/5273257025/jobs/9536456138#step:10:866. Actually this error doesn't affect other installation steps and may be ignored as soon as you handle 2to3 link on your own. For example, to workaround this issue we let brew command to fail on installing Python 3 and then overwriting links with `brew link --overwrite python@3.11`. 

Here are some options for what you can do:
- Wait until [macOS 12 update](https://github.com/actions/runner-images/pull/7727) that includes latest Python 3 version is rolled out
- Do not try to upgrade Python or upgrade it in separate step with forced link override.
- Try running `rm -rf /usr/local/bin/2to3` prior to upgrade.

**Comment by igagis** [comment]
Hi @vpolikarpov-akvelon ! Thanks for analysis.

I decided to go with the third approach of removing `2to3` because this way I will avoid this same problem when new python version comes out.

Though, I had to remove more stuff:
```
        rm -rf /usr/local/bin/2to3*
        rm -rf /usr/local/bin/idle3*
        rm -rf /usr/local/bin/pydoc3*
        rm -rf /usr/local/bin/python3
        rm -rf /usr/local/bin/python3-config
        rm -rf /usr/local/bin/python3*
        rm -rf /usr/local/bin/python3*-config
```

Closing the issue for now.
