### ISSUE TITLE
Installing homebrew + openMPI randomly fails on `macos-latest` runner

### ISSUE THREAD

**Issue by perazz** [actions/runner-images#7742]
### Description

See  https://github.com/fortran-lang/fpm/issues/939

When the CI step works, it runs smooth and fast, e.g.:
https://github.com/perazz/fpm/actions/runs/5303750239/jobs/9599600174
(homebrew openmpi installation step took 29s)

More often, it fails after trying to update plenty of homebrew packages for up to ~30-40 minutes
(sometimes, it seems like the same updates are launched by multiple threads simultaneously). For example: 
https://github.com/fortran-lang/fpm/actions/runs/5303789007/jobs/9599788424

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

2.305.0

### Is it regression?

It appeared recently

### Expected behavior

OpenMPI is pulled from a brew bottle, its installation should be nearly instantaneous and more importantly it should work just fine.

### Actual behavior

Installation fails after a long time trying to upload all sorts of homebrew packages: 

https://github.com/fortran-lang/fpm/actions/runs/5303789007/jobs/9599788424

### Repro steps

Run action 'metapackage-tests' from fortran-lang/fpm

https://github.com/fortran-lang/fpm/actions/workflows/meta.yml

**Comment by sergei-pyshnoi** [comment]
Hello @perazz . We will take a look.

**Comment by mikhailkoliada** [comment]
Hello!

In your build you are running two different image versions, one from May and one from June, as described here: https://github.com/actions/runner-images/issues/7660. The error you see is not random and expected because of python upgrade conflicts in the image version from May. To fix this you can add `brew install python@3.11 || brew link --overwrite python@3.11` to your workflow. Sorry for inconvenience caused! 

If you have questions feel free to reach us out again.

**Comment by perazz** [comment]
Thank you for pointing this out @mikhailkoliada. While the runner images even out, we are forcing no updates to brew dependencies via `HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1`.
