### ISSUE TITLE
Add custom pre-installed dependency version choice

### ISSUE THREAD

**Issue by hemarina** [actions/runner-images#7921]
### Tool name

custom pre-installed dependency version

### Tool license

N/A

### Add or update?

- [X] Add
- [ ] Update

### Desired version

N/A

### Brief description of tool

I'm using ubuntu runner images on our project to trigger GitHub actions. The future pre-installed dependency version updates may bring in breaking changes and cause errors on our project. To prevent that, we install the specific version of dependency in yml file.  May I ask if you have any plans to let users custom pre-installed dependency version? 

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by vpolikarpov-akvelon** [comment]
Hey @hemarina. Could you elaborate your question a bit? What kind of dependencies you are talking about? Could you give an example or provide more context?

**Comment by vpolikarpov-akvelon** [comment]
Well, I'm closing this issue. Feel free to file a new one with more details if your question is still relevant.

**Comment by vpolikarpov-akvelon** [comment]
Hey @hemarina. As you already found yourself there are three versions of Node.js in Ubuntu 22.04 runner. You may either quickly switch between them or install any version you want from external source. We can't provide a lot of different versions of a single software component as it wouldn't be enough space for all of them in runner image. Neither we can serve different versions for each of runner image flavor because of special aspects of GitHub Actions infrastructure.

If you need some special tools and you don't want to waste time installing them in workflow then you may try using self-hosted runners.
