### ISSUE TITLE
User vsts has incorrect primary group

### ISSUE THREAD

**Issue by alex-matei** [actions/runner-images#8184]
### Description

The primary group for vsts is incorrect and causes problems in some pipelines. Please change the group to what was before, vsts with id 1001.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Runner Image
Image: ubuntu-22.04
Version: 20230821.1.0
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230821.1/images/linux/Ubuntu2204-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230821.1

### Is it regression?

yes, 20230814.1.0

### Expected behavior

The primary group id should be vsts, not docker group.

### Actual behavior

Primary group is 999, which is docker.

### Repro steps

Run `id` and look at the primary group for vsts user. Building Kata containers in DevOps fails because of this:

```
git clone https://github.com/kata-containers/kata-containers.git
make -f kata-containers/tools/packaging/kata-deploy/local-build/Makefile rootfs-initrd-tarball
```

Building with the previous version, 20230821.1.0, worked.

**Comment by alex-matei** [comment]
Hi @vpolikarpov-akvelon . Sure, here is the log for the following task:

```
  - bash: |
      git clone https://github.com/kata-containers/kata-containers.git
      pushd kata-containers
      git checkout 3.1.3
      DOCKER_BUILDKIT=0 make -f tools/packaging/kata-deploy/local-build/Makefile rootfs-initrd-tarball
      popd
```

It worked with the old version of the agent. It simply fails with `groupadd: GID '999' already exists` on the latest devops agent.

[bash.log](https://github.com/actions/runner-images/files/12454952/bash.log)

**Comment by vpolikarpov-akvelon** [comment]
After reviewing the details you've provided, it appears that the issue is related to the creation of a group inside a Docker container with an ID that matches the 'docker' group on the host machine. On the GitHub Actions runner, this ID conflicts with an existing group within the container, leading to build failures.

This issue is not a regression and may have arisen as a result of migration from Docker packages hosted by Azure to official Docker packages. These transitions can sometimes introduce unforeseen compatibility challenges.

To address the issue, I recommend reaching out to the Kata Containers development team. They should be able to adjust the build process to better accommodate GH Actions runner's environment. Alternatively, you could consider making adjustments to the build process on your own to avoid conflicts with group IDs inside the container.

**Comment by alex-matei** [comment]
Indeed, I investigated further, the gist of it is that the docker GID on devops agent seems to have changed to 999 and it collides with the GID that docker install script already creates.

I made a small workaround in the pipeline by changing the docker group id to some other value and restarting docker:

```
sudo groupmod -g 998 docker
sudo systemctl restart docker
```

Thanks for taking time to investigate.

**Comment by vpolikarpov-akvelon** [comment]
I'm glad you found a solution. Feel free to reach out again if you have other questions.
