### ISSUE TITLE
[error]The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.

### ISSUE THREAD

**Issue by mathieuboudreau** [actions/runner-images#8333]
### Description

Runner shutdowns in the middle of our conda env install step for Ubuntu and Windows. 

"[error]The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled."

No changes were made internally to our software to trigger this, but maybe there was to one of our dependencies/runners/Github resources?

Tried debugging it by clearing out my env file and adding one by one, stopped when the error first occured, removed that dependency and added the next one and it triggered the same error. So likely a memory issue stemming from conda conflict management, but it's difficult to debug as 1) the miniconda install addon doesn't appear to have verbosity option 2) the output logs only says it's being shut down for ubuntu and memory limit reached for windows (but what memory? ram/space/cpu?), and 3) Tried this https://github.com/marketplace/actions/workflow-telemetry tool to monitor memory usage during this step, but it doesn't output its report for Ubuntu/Windows because of the immediate shutdown (Mac report looks normal).

See our PR debugging this: https://github.com/axondeepseg/axondeepseg/pull/756 

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

2.309.0

Failed build: https://github.com/axondeepseg/axondeepseg/actions/runs/6236507561/job/16927973102#logs

Last build that passed (5 days ago): https://github.com/axondeepseg/axondeepseg/actions/runs/6181019195/job/16787172425

### Is it regression?

No

### Expected behavior

Conda install goes through. Bug happened without changes to the software, it was detected on an overnight automated test.

### Actual behavior

Linux and Windows tests now failing.

### Repro steps

Github actions file: https://github.com/axondeepseg/axondeepseg/blob/master/.github/workflows/run_tests.yaml

**Comment by mahdiar-naufal-shyftplan** [comment]
It looks like you have a similar problem with this discussion (https://github.com/actions/runner-images/discussions/7188).

**Comment by erik-bershel** [comment]
Hey @mathieuboudreau!
I doubt that the problem lies in the image - from the history of running tests in your repository, I see that red and green runs exist on the same image of ubuntu-22.04 (20230911.1.0), which means it cannot be related to updates of the image itself.
Let me try to collect as much information as possible that may help in finding the reasons. This is a very common problem. The [discussion](https://github.com/actions/runner-images/discussions/7188) on this topic is perhaps the most popular.
From the runner history I may say next:
- https://github.com/axondeepseg/axondeepseg/actions/runs/6231217029/job/16912426816 - ran out of RAM
- https://github.com/axondeepseg/axondeepseg/actions/runs/6231217029/job/16912427056 - ran out of RAM
- https://github.com/axondeepseg/axondeepseg/actions/runs/6193967674/job/16816263071 - ran out of CPU
- https://github.com/axondeepseg/axondeepseg/actions/runs/6193967674/job/16816263277 - ran out of RAM
- https://github.com/axondeepseg/axondeepseg/actions/runs/6181019195/job/16778360528 - random failure, didn't use all resources

We can only recommend to optimise build process or to ask community to help you with it.

**Comment by erik-bershel** [comment]
@mathieuboudreau internal resources, unfortunately there is no information there that would allow us or you to localise the issue. You may ask us to provide info about failed runs of this type if you need it.

**Comment by mathieuboudreau** [comment]
Ok no worries, just wanted to make sure I didn't miss something - appreciate it!

**Comment by mathieuboudreau** [comment]
Resolved it on my end, documenting it here in case someone finds this thread in the future. Removing the conda-forge channel and moving the necessary packages that aren't in the default channel to pip in the environment file fixed it : https://github.com/axondeepseg/axondeepseg/pull/756/files 

The CI runs through quickly and without memory problem now: https://github.com/axondeepseg/axondeepseg/actions/runs/6239345090/job/16937069377?pr=756
