### ISSUE TITLE
Virtualization is not enabled error on macos13 M1 runner

### ISSUE THREAD

**Issue by balajiv113** [actions/runner-images#8465]
### Description

Hi,
With the new macos-13-xlarge runner. We are getting Virtualization is not enabled in this hardware error.

Previously, in macos-13 this was working fine

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/lima-vm/lima/actions/runs/6404371464/job/17384805822?pr=1879

### Is it regression?

No

### Expected behavior

Virtualization machine running fine in macOS M1 runner 

### Actual behavior

Virtualization machine throwing error in macOS M1 runner 

### Repro steps

Run lima in macos-13-xlarge runner

**Comment by Alexey-Ayupov** [comment]
Hello @balajiv113. We will take a look.

**Comment by Alexey-Ayupov** [comment]
According to this [article ](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#limitations-for-macos-larger-runners): "`Due to a limitation of Apple's Virtualization Framework, which our hypervisor uses, nested-virtualization is not supported by arm64 runners.`"

So you can proceed with the `macos-13`  or `macos-13-large` runners.
I will close this issue. If you have other questions feel free to reach us.
