### ISSUE TITLE
Incomplete output - ##[error]Bash exited with code '100'.

### ISSUE THREAD

**Issue by AzaruddinKhan** [actions/runner-images#8729]
### Description

Hi,
I am using vmImage: "ubuntu-22.04" to run the test classes in Salesforce & return the result after the execution.

What I observed is that after the execution the output is not completed populated & in a result the job fails with below exception .
**error ##[error]Bash exited with code '100'.**

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

NA.

### Is it regression?

No, it's vmImage: "ubuntu-22.04" 

### Expected behavior

It should generate the complete output and should go to next step for job closure.

### Actual behavior

I am using vmImage: "ubuntu-22.04" to run the test classes in Salesforce & return the result after the execution.

What I observed is that after the execution the output is not completed populated & in a result the job fails with below exception .
**error ##[error]Bash exited with code '100'.**

### Repro steps

Use the image vmImage: "ubuntu-22.04" & run all the test classes of the org in with the below command.

**sfdx force:apex:test:run -u codecoverage -l RunLocalTests -c -r human --synchronous**

<img width="1380" alt="Screenshot 2023-11-03 at 11 55 07 AM" src="https://github.com/actions/runner-images/assets/67893561/d56a2730-2bf9-4e91-9c94-83bd418ad77b">

**Comment by erik-bershel** [comment]
Hello @AzaruddinKhan ! 
A few clarifying questions: 
- Have these tests worked before? If they worked, then from what version of the image did they stop working? 
- Is the behaviour different on Ubuntu-20? If you haven't tried checking this out, it would be great if you give it a try. 
- And finally, could you provide a minimal project in which the specified behaviour is repeated? We need a code example and an example pipeline on which we can test the problem and understand where its root is.

**Comment by AzaruddinKhan** [comment]
Hi @erik-bershel  ,

Thanks for your response!
I am using  vmImage: "**ubuntu-22.04**" at the moment , let me try with vmImage: **"ubuntu-20.04**" and get back to you with the outcome.

**Comment by AzaruddinKhan** [comment]
Hi @erik-bershel  ,

I have tried with vmImage: "**ubuntu-20.04**" , the issue still persists.

<img width="930" alt="Screenshot 2023-11-10 at 11 27 26 AM" src="https://github.com/actions/runner-images/assets/67893561/8720d12d-1222-49a2-86b2-454db7fafbdd">

**Comment by erik-bershel** [comment]
@AzaruddinKhan it's bad. Looks we need some repro steps to check what happen under the hood of your action. Since we are not familiar with this particular system I need to get some example workflow or simple project. It would be very nice if you built a public demo-project but sharing source-code here is an option too.
I tried to check what can I do about it on my own but it seems like it's obligatory to have fully-paid Salesforce account which is not an option for us. I will be glad if you correct me on this issue.

**Comment by erik-bershel** [comment]
Hey @AzaruddinKhan! I'm going to close this item due to inactivity. Please feel free to reach me here if you found any updates or questions, and any way you may open new issues in case of other concerns.

I would also like to add that, taking into account the information received, this looks more like an error related to updating the Salesforce cli. But it's hard to say anything with certainty without complete information and the opportunity to repeat the mistake. I can recommend contacting the sfdx apex [repository](https://github.com/forcedotcom/salesforcedx-apex/issues) with the same problem and trying to repeat the behavior in the local environment. In the first case, maintainers will have more tools to find the source of problems; in the second, it will be possible to at least eliminate some of the possible causes.

**Comment by ferpaxecosanxez** [comment]
This scenario is typical when you are using Salesforce CLI commands, i.e., each Salesforce command can return a value "0" (OK) or value "!=0" (ERR)...

So, in your case, you are running the command:
```
sfdx force:apex:test:run -u codecoverage -l RunLocalTests -c -r human --synchronous
```

The command return a value "1". The exit code 1 from the Salesforce CLI command indicates that there were errors during the execution of the tests, which in your case is true

Well... why does my pipeline break? Because when Saleforce command return the executed code, the pipeline picks it up and if it is "1", i.e. there is an error, it returns the same

How is it solved? In your script, you need capture the exit code of the command with:

```
local fileExecLog="$FOLDER_TEMP/exec-log.txt"
local fileExecLogCode="$FOLDER_TEMP/exec-log-code.txt"

## Run the organization test and save the results in the temporary folder
local runSalesforceTest=$(sfdx force:apex:test:run -u codecoverage -l RunLocalTests -c -r human --synchronous)

## Redirect StdOut and StdErr. Get exit code to save in temporal file
local execCommand=$($runSalesforceTest &> $fileExecLog; echo $? &> $fileExecLogCode)
```

You can use this file to check if the command completed successfully or if there were errors. Note that I use the `execCommand` variable to mask it, i.e., I have return value "0" (OK) and my pipeline doesn't break ;)
