### ISSUE TITLE
Error: LinkageError occurred while loading main class com.android.sdklib.tool.sdkmanager.SdkManagerCli

### ISSUE THREAD

**Issue by littleGnAl** [actions/runner-images#8761]
### Description

The github action run failed with an error in recent days when using the runner `macos-13`:
```
  Error: LinkageError occurred while loading main class com.android.sdklib.tool.sdkmanager.SdkManagerCli
  	java.lang.UnsupportedClassVersionError: com/android/sdklib/tool/sdkmanager/SdkManagerCli has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Image: macos-13
  Version: 20231025.2
  Included Software: https://github.com/actions/runner-images/blob/macos-13/20231025.2/images/macos/macos-13-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-13%2F2023[10](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/actions/runs/6784313850/job/18452944744#step:1:11)25.2
```

Failed build
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/actions/runs/6784313850/job/18452944744?pr=1425

### Is it regression?

https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/actions/runs/6717135812/job/18263129067?pr=1418

### Expected behavior

Can install the android build tools successfully

### Actual behavior

Failed with error:
```
  Error: LinkageError occurred while loading main class com.android.sdklib.tool.sdkmanager.SdkManagerCli
  	java.lang.UnsupportedClassVersionError: com/android/sdklib/tool/sdkmanager/SdkManagerCli has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

### Repro steps

Use the runner `macos-13` should reproduce this issue.

**Comment by mikhailkoliada** [comment]
hey! that is ok, you seem to run java-17 compatible sdkmanager against the java-11 environment, you should re-configure your setup-java workflows

**Comment by littleGnAl** [comment]
I did re-configure the jdk version
<img width="767" alt="image" src="https://github.com/actions/runner-images/assets/8847263/4f253c10-e6b7-45cf-94bd-e5ed4ad9e2fd">

You can find the step here
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/actions/runs/6784313850/job/18452944744?pr=1425

**Comment by littleGnAl** [comment]
After switching to `macos-12`, it works fine now, 
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/actions/runs/6794611263/job/18471299817?pr=1428

**Comment by erik-bershel** [comment]
Hey @littleGnAl!

The error is that you are trying to install the latest Android SDK Manager CLI on macOS 13, which requires version **17** of Java while your workflow uses **11**. Please, take a look [here](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/6106a4386653b4d1326c848ea5372d3b2885fbee/.github/workflows/build.yml#L85C1-L86C1). By switching to an older OS, you get a different version of the SDK in action, which allows you to use an older version of Java. 
In any case, the problem is not in the image but in the configuration. Perhaps on the action side, since I don’t see the point in putting into the image what is already there as it done here: https://github.com/ReactiveCircus/android-emulator-runner/blob/main/src/sdk-installer.ts.

If you still have questions related to this error, you can still ask them here. In case of other concerns, please feel free to open new issues.

**Comment by torexanovich** [comment]
i have similar issue on linux 23.10 but still can't fix it. Anybody faced the same?
