### ISSUE TITLE
Old versions of Android SDK & tools will be removed from images on January, 8

### ISSUE THREAD

**Issue by mikhailkoliada** [actions/runner-images#8952]
### Breaking changes

Android SDK & tools v19 through v30 will be removed from Windows 2019 image.
Android SDK & tools v27 through v30 will be removed from Windows 2022 and all Ubuntu and macOS images.

### Target date

The images rollout process will start on January 8 and take 3-4 days.

### The motivation for the changes

We would like to remove some obsolete versions and free up more disk space on runner agents.

### Possible impact

If your workflows or pipelines depend on these older version of components, they may be broken.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Mitigation ways

Nothing specific is required. All the components can still be installed using Android's [sdkmanager](https://developer.android.com/tools/sdkmanager).

**Comment by ysmoradi** [comment]
I successfully configured GitHub Actions hosted agents to enable the .NET MAUI Android build by adding the following snippet to the YAML file:
```yaml
- name: Setup Android SDK
  uses: android-actions/setup-android@v3
  with:
    cmdline-tools-version: 9477386
```
Now, I need assistance with Azure DevOps pipelines. Unfortunately, I couldn't find any suitable task in the marketplace for this purpose. If I decide to use `sdkmanager` to achieve this, could you guide me on the parameters to pass to its install command?

Regarding [PR #4301](https://github.com/slint-ui/slint/pull/4301), is it intended to resolve the issue? I'm concerned about potential disruptions to CI/CD pipelines for projects relying on Microsoft's recommended approach for building Android apps with .NET MAUI /-:

@tronical

**Comment by ysmoradi** [comment]
Based on official [.NET MAUI docs](https://learn.microsoft.com/en-us/dotnet/maui/get-started/installation?view=net-maui-8.0&tabs=visual-studio-code#theres-an-error-that-the-android-sdk-or-java-sdk-was-not-found) It's relying on `cmdline-tools` v7
![image](https://github.com/actions/runner-images/assets/5352980/e24604be-8852-4e8e-a4e2-6977b67d1d79)

**Comment by ysmoradi** [comment]
For those who are struggling with this in .NET MAUI, run this command and you're good to go:
`-t:InstallAndroidDependencies -f:net8.0-android -p:AcceptAndroidSDKLicenses=True`

**Comment by shichen85** [comment]
https://github.com/actions/runner-images/blob/a89e382279a91339e9afe0d7477a8bb1f087670f/images/ubuntu/Ubuntu2204-Readme.md?plain=1#L258 mentioned that platform tools 34.0.5 is included in this image.

We use `/usr/local/lib/android/sdk/platform-tools/adb`, and I see that version 34.0.5 still has it in the `platform-tools` dir, but now we are getting the error 
`System.ComponentModel.Win32Exception (2): An error occurred trying to start process '/usr/local/lib/android/sdk/platform-tools/adb' with working directory '/home/runner/work/out'. No such file or directory` 

Is this temporary because of the migration, or do we need to install adb ourselves?

**Comment by DosangGu** [comment]
> For those who are struggling with this in .NET MAUI, run this command and you're good to go: `dotnet build -t:InstallAndroidDependencies -f:net8.0-android -p:AcceptAndroidSDKLicenses=True -p:AndroidSdkPath="/usr/local/lib/android/sdk/"`

Also successed with temporary solution below.
```yml
      - name: Set Up Android tools
        run: |
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager \
          --sdk_root=$ANDROID_SDK_ROOT \
          "platform-tools"

      - name: Build
        run: |
          dotnet build <project> \
          -f:net8.0-android
```

**Comment by Blue101black** [comment]
For .NET Xamarin, this is what I did for a windows-2022 pipeline to fix it.

Add this Command Line task before your Xamarin.Android task

```yaml
steps:
- script: |
   C:\Android\android-sdk\cmdline-tools\latest\bin\sdkmanager "platforms;android-28"
   
   C:\Android\android-sdk\cmdline-tools/latest/bin/sdkmanager "build-tools;28.0.3"
   
  displayName: 'Install Android API 28'
```

**Comment by mikhailkoliada** [comment]
Removed.

**Comment by cmeeren** [comment]
> Also successed with temporary solution below.
> 
> ```yaml
>       - name: Set Up Android tools
>         run: |
>           ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager \
>           --sdk_root=$ANDROID_SDK_ROOT \
>           "platform-tools"
> 
>       - name: Build
>         run: |
>           dotnet build <project> \
>           -f:net8.0-android
> ```

Thanks a lot! This was what worked for me. The solution described by @ysmoradi in https://github.com/actions/runner-images/issues/8952#issuecomment-1882923510 didn't work, because I get the error described by @hansmbakker in https://github.com/actions/runner-images/issues/8952#issuecomment-1884552362 every single time ("The Android SDK directory could not be found").

To @mikhailkoliada or whomever it may concern: This unexpected change cost me several hours of work. Firstly, it would be great if there were pipeline warnings (visible on the main build result page) for a long sunset period before such changes occur, to increase the chance that devs pick this up and can prepare for it, instead of finding out only when trying to build a (possibly urgent) app update. Secondly, it would be great if the official solution actually worked. 😅

**Comment by Falco20019** [comment]
The `Android SDK Platform-Tools` got removed completely. Was this on purpose? it was only announced that *old* APIs and tools are to be removed. The platform-tools were up2date and should IMHO not be removed.

**Comment by Hanmac** [comment]
@Falco20019 would https://github.com/android-actions/setup-android help with installing/finding the sdkmanager or is that broken too?

**Comment by Falco20019** [comment]
@Hanmac I would assume that this should still work since according to the description, it should install the SDK and platform-tools even if nothing was pre-installed.

I can give it a try later today, but just calling the already installed sdkmanager was the quickest solution. I can compare the time it takes using the action. Using the sdkmanager, it currently adds only 12 seconds to the build time.

**Comment by Blue101black** [comment]
> For .NET Xamarin, this is what I did for a windows-2022 pipeline to fix it.
> 
> Add this Command Line task before your Xamarin.Android task
> 
> ```yaml
> - script: |
>    C:\Android\android-sdk\cmdline-tools\latest\bin\sdkmanager "platforms;android-28"
>    
>    C:\Android\android-sdk\cmdline-tools/latest/bin/sdkmanager "build-tools;28.0.3"
>    
>   displayName: 'Install Android API 28'
> ```

Getting this warning that I did not notice after fixing the failing pipeline.

```
C:\Program Files (x86)\Android\android-sdk\tools\proguard\proguard-android.txt(0,0): Warning XA4304: ProGuard configuration file 'C:\Program Files (x86)\Android\android-sdk\tools\proguard\proguard-android.txt' was not found.
```

Has Proguard been removed or moved? How can I fix this?

This is causing the built APK to crash when rendering animations from the AirBnb Lottie package.

Azure DevOps

**Comment by BrianMouncer** [comment]
Ok, so you removed older Android SDK, but did you actively go out of your way try to make it had to manually install them. ;-)

It seems the latest Android Studio and SDK no longer install sdkmanager.bat by default under $ANDROID_HOME/tools
It looks like these are all now an optional package called cmdline_tools

unfortunately, you did not install this optional tools package when you removed the older SDKs and since the SDKManager command line is now one of the missing tools, it is not possible to fix this without using the SDK manager UI in Android studio to install the tools package or the missing android platform packages...

The only way I could work around this was to CURL download the latest cmdline_tools zip file from google, and then upzip it to where is should be under "$ANDROID_HOME/cmdline-tools", and then use sdkmanger commandline to install the needs Android SDKs.

It would be very helpful and kind if you installed the optional cmdline-tools package so that users can use sdkmanager to install the platform API levels that you removed from the default agent images...

Thanks,

**Comment by SuperJMN** [comment]
OK, this is nasty. I'm running `dotnet workload restore MySolution.sln` just before building my solution in Azure Pipelines ubuntu-latest, and even though getting this:

> ##[error]/usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/33.0.95/tools/Xamarin.Android.Tooling.targets(70,5): error XA5300: The Android SDK directory could not be found. Install the Android SDK by following the instructions at: https://aka.ms/dotnet-android-install-sdk [/home/vsts/work/1/s/src/AvaloniaSyncer.Android/AvaloniaSyncer.Android.csproj]

I assume that **restoring workloads should care about installing the required Android SDK and everything**. Why is the Android application different from any other when it comes to building? If it requires something, install it. 

That's common sense, isn't it?

BTW, none of the solutions above applies to my scenario because I'm using Nuke build. I'm building withi this code: https://github.com/SuperJMN/AvaloniaSyncer/blob/8dbcd7de17e7b890a5071a5accdcdb674dafa7bf/build/Build.cs#L40

Please, fix this ASAP.

**Comment by Falco20019** [comment]
@SuperJMN The path to the SDK is /usr/local/lib/android/sdk, you should be able to call it also there als Shell command

**Comment by Blue101black** [comment]
Anyone have a solution for the `C:\Program Files (x86)\Android\android-sdk\tools` directory now missing in windows-2022 image?

![image](https://github.com/actions/runner-images/assets/55679074/2e74f392-cfc1-4c57-8b46-9ef886ac3f61)

Need the Proguard folder to exist.

My Xamarin Forms Android build now gets this warning:
```
C:\Program Files (x86)\Android\android-sdk\tools\proguard\proguard-android.txt(0,0): Warning XA4304: ProGuard configuration file 'C:\Program Files (x86)\Android\android-sdk\tools\proguard\proguard-android.txt' was not found.
```

Which results in a run-time crash of the built APK 😨

**Comment by Falco20019** [comment]
@Blue101black According to https://developer.android.com/build/shrink-code ProGuars was replaced by R8. You might need to adjust your tooling accordingly.

**Comment by cjp666** [comment]
I am having to change my Xamarin.Forms application to target a later version of the Android SDK because of this removal.  I've changed nothing other than the "Target Android version", from "API Level 29" to "API Level 34".  The vm image is "windows-2022" and the XamarinAndroid@1 step fails with "An exception has occurred in the compiler (1.8.0_392). Please file a bug against the Java compiler via the Java bug reporting page"

I've changed the build yml to use the "windows-2019" vm image and that hangs on the same step.  After an hour, DevOps cancels the build

Don't know where I go from here, any suggestions will be much appreciated

**Comment by cjp666** [comment]
@Blue101black you are a star, thank you

Adding 
- script: |
    C:\Android\android-sdk\cmdline-tools\latest\bin\sdkmanager "platforms;android-29"
    displayName: 'Install Android API 29'

As the step before my XamarinAndroid@1 step sorted it for me

No ProGuard issues for me

**Comment by SuperJMN** [comment]
> @SuperJMN The path to the SDK is /usr/local/lib/android/sdk, you should be able to call it also there as Shell command:
> 
> /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/usr/local/lib/android/sdk "platform-tools"
> 
> I also find it frustrating that Android builds have some more dependencies not dealt with by the workload. There is a dotnet global tool that helps with setting up prequisites that we use on our machines. But was not necessary on the runners so far: https://github.com/Redth/dotnet-maui-check

I'm sorry. I can't understand what you suggest. This issue mentions that "Android SDKs and tools" are deleted, so no longer available as part of the runner images. That is breaking my Android builds. So, how to install those tools manually to make my Android builds work again?

I guess it's a matter of installing it manually, but how?

Thank you!

**Comment by SuperJMN** [comment]
> @Blue101black you are a star, thank you
> 
> Adding
> 
> * script: |
>   C:\Android\android-sdk\cmdline-tools\latest\bin\sdkmanager "platforms;android-29"
>   displayName: 'Install Android API 29'
> 
> As the step before my XamarinAndroid@1 step sorted it for me
> 
> Need to run it now and see if there are any proguard errors

What's the equivalent in "powershell" so it can run in whatever image? 
Thanks!

**Comment by cjp666** [comment]
@Blue101black I'm not getting any proguard errors, everything runs fine for me

@SuperJMN I think in the powershell script you should just be able to run 
C:\Android\android-sdk\cmdline-tools\latest\bin\sdkmanager.exe "platforms;android-29"

**Comment by Falco20019** [comment]
@SuperJMN This will not work for you as it's for Windows. According to your error message you use Ubuntu.

They did not mention that `Android SDKs and tools` are removed. Only OLD are removed. But they seem to have also deleted one of the tools accidentally (platform-tools) which is needed by most of us... So the only thing missing for you is to install them.

I never worked with Nuke, but I would assume, that it should look something like this for you:
```
    Target RestoreAndroidPlatformTools => td => td
        .Executes(() =>
        {
            StartShell(@"/usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/usr/local/lib/android/sdk \"platform-tools\"").AssertZeroExitCode();
        });
```

Just make sure to have `RestoreAndroidPlatformTools` as dependency before you try to run your build.

**Comment by TeemuToivanen** [comment]
> @Blue101black you are a star, thank you
> 
> Adding
> 
> * script: |
>   C:\Android\android-sdk\cmdline-tools\latest\bin\sdkmanager "platforms;android-29"
>   displayName: 'Install Android API 29'
> 
> As the step before my XamarinAndroid@1 step sorted it for me
> 
> Need to run it now and see if there are any proguard errors

Thanks, that fixed my Xamarin Android build issue!

**Comment by saied20** [comment]
How does this relate to Appcenter? Does it use the same agent?
I noticed builds with Android sdk < 31 don't work there as well.

**Comment by mikhailkoliada** [comment]
Cleaned up.

**Comment by sergeylv9** [comment]
Success with this solution (GitHub Actions)

  - name: Setup Android SDK 27, 28, 29 and 30
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 9123335
    - run: sdkmanager tools "platforms;android-27" "platforms;android-28" "platforms;android-29" "platforms;android-30"

**Comment by StephenWithPH** [comment]
> Is this temporary because of the migration, or do we need to install adb ourselves?

@shichen85, did you ever receive an answer to your question?

I'm also seeing `/usr/local/lib/android/sdk/platform-tools/adb: No such file or directory` .

**Comment by shichen85** [comment]
> > Is this temporary because of the migration, or do we need to install adb ourselves?
> 
> @shichen85, did you ever receive an answer to your question?
> 
> I'm also seeing `/usr/local/lib/android/sdk/platform-tools/adb: No such file or directory` .

I don't think I have gotten a reply. I ended up installing adb myself as many other suggested with something similar to:

```
      - name: Set Up Android tools (non-windows runner only)
        if: ${{ !startswith(inputs.runner, 'windows') }}
        run: |
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager \
          --sdk_root=$ANDROID_SDK_ROOT \
          "platform-tools"
```
