### ISSUE TITLE
Add databases to Mac OS Arm64 images?

### ISSUE THREAD

**Issue by pamelafox** [actions/runner-images#9029]
### Tool name

macos-latest-xlarge

### Tool license

Varies

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Same version as in other images, or higher

### Brief description of tool

The other images have Postgres and MongoDB. It'd be great if the ARM64 image also had those databases, to enable easy CI testing.

### Provide a basic test case to validate the tool's functionality.

```bash
See other images.
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
Yes. We're using brew to do it ourselves, but you could use different tools.
```

### Tool installation time in runtime

Same as other images.

### Are you willing to submit a PR?

If necessary, but tool installation isn't my expertise

**Comment by erik-bershel** [comment]
Hello @pamelafox! 
We understand your concern - this is an important issue for many. We'll get back to you with an answer after some investigation.

**Comment by mikhailkoliada** [comment]
Hello! We would not like to pre-install databases to arm64 images due to maintenance concerns and also pretty low demand on macOS specifically.

**Comment by karlhorky** [comment]
> pretty low demand on macOS specifically

@mikhailkoliada interesting, where does this data come from? Maybe users don't know that it's available?

I would assume that this would be about the same amount of demand as Linux / Windows, and it seems unusual that it's only unavailable on this version of macOS, but it's available everywhere else.

> due to maintenance concerns

Would also be interested where the perception of higher maintenance cost comes from. We've been [teaching beginners to install and maintain PostgreSQL on their systems](https://github.com/upleveled/system-setup/blob/main/macos.md) since the Apple Silicon machines appeared, and we haven't noticed any specific higher maintenance effort with this platform - upgrades have been straightforward, and any new incompatibilities have mainly stemmed from PostgreSQL itself, affecting all platforms (also resolved with the same solution across all platforms). But maybe `actions/runner-images` wants to achieve a more complex configuration which is somehow harder to maintain?
