### ISSUE TITLE
Add [aws copilot] to ubuntu

### ISSUE THREAD

**Issue by geekodour** [actions/runner-images#9325]
### Tool name

aws copilot

### Tool license

 Apache License

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

The AWS Copilot CLI is a tool for developers to build, release and operate production ready containerized applications on AWS App Runner or Amazon ECS on AWS Fargate. 
 
We already have aws tooling in github hosted runners. aws copilot is cli tool to deploy ecs containers in an aws opinionated way. This has several benefits.
 
 Currently people have been using things like: https://github.com/ksivamuthu/aws-copilot-github-action

### URL for tool's homepage

https://github.com/aws/copilot-cli

### Provide a basic test case to validate the tool's functionality.

```bash
copilot deploy
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
Yes
```

### Are you willing to submit a PR?

Yes

**Comment by MaksimZhukov** [comment]
Hello @geekodour!
We do not have plans to bake aws copilot into the images due to maintenance concerns and short installation time. Please continue installing in runtime using the [official installation steps](https://github.com/aws/copilot-cli?tab=readme-ov-file#installation) or [community action](https://github.com/ksivamuthu/aws-copilot-github-action).
