### ISSUE TITLE
[Ubuntu, Windows] Az Powershell module will be updated to v11.3.1 on March 18

### ISSUE THREAD

**Issue by mikhailkoliada** [actions/runner-images#9445]
### Breaking changes

Pre-installed Az powershell module on Ubuntu & Windows will be updated to v11.3.1.

### Target date

The image rollout process will be started on March 18th and take 3-4 days.

### The motivation for the changes

We want to provide a more recent version preinstalled.

### Possible impact

If you use direct invocations of Az cmdlets they might be incompatible between major versions of the module so you may need to downgrade your version if it affects your pipeline in workflows unexpected way, we from our side unlikely to help with the code adoption to the new version and most likely all the reports to the runner-images repo will be marked as external and later closed.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Mitigation ways

GitHub:

Use the [azure/powershell](https://github.com/Azure/powershell) action, it lets you to specify a module version you would like using by passing the `azPSVersion` parameter.

Actions:

Use the [AzurePowershell@5](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-powershell-v5?view=azure-pipelines) Azure DevOps task to specify a desired version

**Comment by JADSKTPSVR** [comment]
Love it

**Comment by mikhailkoliada** [comment]
Deployed

**Comment by d3vinda** [comment]
hey @mikhailkoliada  , there is an issue with 11.3.1 which is fixed in 11.4.0.  are we able to pin the new version to be pre-installed in the agents instead of 11.3.1 ??

its related to using what-if flag in deployments and causing failures in pipelines using ubuntu and windows agent images, issue is also mentioned here --> https://github.com/Azure/bicep/issues/12112

**Comment by chromebohemian448** [comment]
"Actions:

Use the [AzurePowershell@5](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-powershell-v5?view=azure-pipelines) Azure DevOps task to specify a desired version"

how to set desired version of Az module? from the link I understand that its the version of Powershell but not of the Az modules
how to downgrade Az module on the MS hosted agents? Thanks

**Comment by d3vinda** [comment]
@chromebohemian448 , used below to install a specific version of Azure PowerShell version.

![image](https://github.com/actions/runner-images/assets/17114376/8ab2e4b8-8c43-424a-a746-cb5e338333e6)

```
azurePowerShellVersion: "OtherVersion"
preferredAzurePowerShellVersion: "11.4.0"
```

Problem with this approach is that it takes time to install Az modules after a new agent is allocated when running the pipeline using Microsoft hosted agents. It also adds additional time if you have parallel stages since you'll be allocated a new agent/s I believe for a paralle stage/s in your pipeline. 

Was hoping versions pinned to `*-latest` images are patched regularly when issues are identified.   
--> https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
--> https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md
![image](https://github.com/actions/runner-images/assets/17114376/ddebb418-0ff6-48bd-8f51-9994fe8ba73a)

References: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-powershell-v5?view=azure-pipelines
https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software

cc: @mikhailkoliada

**Comment by clRecruitment21** [comment]
So I am experiencing an issue with our build pipeline last seen to work on the 21st March - now fails, no code changes.

The 'New-AzSubscriptionDeployment' command was found in the module
'Az.Resources', but the module could not be loaded due to the following
error: [Assembly with same name is already loaded] For more information,
run 'Import-Module Az.Resources'.

We are running New-AzSubscriptionDeployment inside a powershell script that runs from AzurePowerShell@5.

Have tried 
              azurePowerShellVersion: OtherVersion
              preferredAzurePowerShellVersion: 9.3.0
              
Which i think seems to line up with the previous version - and i still get the same error.

I tried changing the ubuntu image too (mainly because I got confused as to when the definition of 'latest' had changed) but i get the same message for pinned ubuntu-20.04 

What is odd if there is very little 'out there' about this error.

if I do as it suggests I get

![image](https://github.com/actions/runner-images/assets/79106058/c2976ab8-2f40-43e9-9049-86321d5de912)

Anyone help?

**Comment by chromebohemian448** [comment]
> So I am experiencing an issue with our build pipeline last seen to work on the 21st March - now fails, no code changes.
> 
> The 'New-AzSubscriptionDeployment' command was found in the module 'Az.Resources', but the module could not be loaded due to the following error: [Assembly with same name is already loaded] For more information, run 'Import-Module Az.Resources'.
> 
> We are running New-AzSubscriptionDeployment inside a powershell script that runs from AzurePowerShell@5.
> 
> Have tried azurePowerShellVersion: OtherVersion preferredAzurePowerShellVersion: 9.3.0
> 
> Which i think seems to line up with the previous version - and i still get the same error.
> 
> I tried changing the ubuntu image too (mainly because I got confused as to when the definition of 'latest' had changed) but i get the same message for pinned ubuntu-20.04
> 
> What is odd if there is very little 'out there' about this error.
> 
> if I do as it suggests I get
> 
> ![image](https://private-user-images.githubusercontent.com/79106058/322458958-c2976ab8-2f40-43e9-9049-86321d5de912.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxODE2MTYsIm5iZiI6MTcxMzE4MTMxNiwicGF0aCI6Ii83OTEwNjA1OC8zMjI0NTg5NTgtYzI5NzZhYjgtMmY0MC00M2U5LTkwNDktODYzMjFkNWRlOTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDExNDE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkM2I2MGM0Zjc0ZDViYTIwYjhlMmYyZmM3Y2FhMjI4YzY5MGE4YzJhZmY3NDIzOGE5Y2FiY2I2ZDY4ZTA0ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sgtE4PraRVyAMZ5-pP9PvWMhFshV-vwjyubCvd7L4gY)
> 
> Anyone help?

go to your script Update-Infrastructure.ps1, then to the line 91, and remove/comment this line "Import-Module Az.Resources"

**Comment by clRecruitment21** [comment]
If i do that, I am back to the highlighted error.

![image](https://github.com/actions/runner-images/assets/79106058/dd9abff3-45b3-43b9-89ed-c8a1949464a5)

I added the import because the error said to try it... but it sheds no light what-so-ever.

I am stumbling around to try and understand what might have changed with the 'ubuntu-latest' which last ran successfully on the 21st March.

Looking further at this you can see the image versions etc here:

WORKED
![image](https://github.com/actions/runner-images/assets/79106058/bb93bb8e-ff6f-49d3-9c93-635c906d4117)

DOESN'T
![image](https://github.com/actions/runner-images/assets/79106058/fa4a3a5e-adcc-4406-9ccb-1bc42ba888f8)

**Comment by clRecruitment21** [comment]
it may be relevent it may not.. but notice that the 
![image](https://github.com/actions/runner-images/assets/79106058/c553773a-0c25-43e2-ae39-7407d7660e43)
AzurePowerShell version has changed.

**Comment by clRecruitment21** [comment]
If i compare the 'included software' between the two reported urls
OLD:
https://github.com/actions/runner-images/blob/ubuntu22/20240317.1/images/ubuntu/Ubuntu2204-Readme.md?plain=1

NEW:
https://github.com/actions/runner-images/blob/ubuntu22/20240407.1/images/ubuntu/Ubuntu2204-Readme.md?plain=1

You can see an announcement "Az Powershell module will be updated to v11.3.1" however across both versions new and old it is/already 11.3.1

and the link it refers to is here...

**Comment by clRecruitment21** [comment]
So @chromebohemian448's message appears to have disappeared.. you were asking me to remove the 'import' I'd added as the error advised. See my findings.

However, I have noticed that in the same time window an awesome package we use 'RegionOrebroLan.Transforming' had changed a version number, and reverting this back - our error disappears. 

I have no idea at this stage what they could have changed, but the thrust of my investigation goes that way now.

@jonathh21

**Comment by Ottapettavan** [comment]
Import
