### ISSUE TITLE
Endless AddressSanitizer:DEADLYSIGNAL loop with GCC 13 since Ubuntu 22.04 202403**10**.1.0 but not before

### ISSUE THREAD

**Issue by hartwork** [actions/runner-images#9524]
### Description

Workflow https://github.com/cpptest/cpptest/blob/master/.github/workflows/linux.yml was working [fine](https://github.com/cpptest/cpptest/actions/runs/8198156643/job/22421247085) until a few days agao with image 202403**04**.1.0 and now the same commit (https://github.com/cpptest/cpptest/commit/4430bb3a2f484359d06dd6c92fdafdba2a633c9d if curious) with image 202403**10**.1.0 is [failing](https://github.com/cpptest/cpptest/actions/runs/8290749936/job/22726589918) with GCC 13 (but not Clang 18!) looping runtime error `AddressSanitizer:DEADLYSIGNAL?` and then timing out.

Could be the same cause as #9491 but #9491 seems to be about Clang instead of GCC.

CC @hannob

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Good: 202403**04**.1.0
Bad: 202403**10**.1.0

Good: https://github.com/cpptest/cpptest/actions/runs/8198156643/job/22421247085
Bad: https://github.com/cpptest/cpptest/actions/runs/8290749936/job/22726589918

### Is it regression?

20240304.1.0

### Expected behavior

CI finishes in under 2 minutes

### Actual behavior

CI times out after a seeming endless loop from GCC 13 ASan saying `AddressSanitizer:DEADLYSIGNAL?`.

### Repro steps

Re-run https://github.com/cpptest/cpptest/actions/runs/8290749936/job/22726589918 and watch output of "make all".

**Comment by phil-blain** [comment]
It's the same cause, GCC uses the same sanitizers as Clang does [[source]](https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=libsanitizer/README.gcc;h=07defc5b6d8700803e402f0e2ea70d7854c2d769;hb=cc035c5d8672f87dc8c2756d9f8367903aa72d93).

In stock GCC 13.1.0, which is [the version in the `ubuntu-22.04` images](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#language-and-runtime), the sanitizers are merged from LLVM commit llvm/llvm-project@ae59131d3ef311fb4b1e50627c6457be00e60dc9 [[source]](https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=libsanitizer/MERGE;h=6bb19c7d5ba81bcc0a3aa622ba5f262841414da6;hb=cc035c5d8672f87dc8c2756d9f8367903aa72d93). The same version is used in GCC 13.2.0 [[source]](https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=libsanitizer/MERGE;h=6bb19c7d5ba81bcc0a3aa622ba5f262841414da6;hb=c891d8dc23e1a46ad9f3e757d09e57b500d40044).

This commit was released as part of LLVM 16.0.0, and thus predates the fixes to AdressSanitizer to make it compatible with the changes in the Ubuntu azure kernel package (version [`6.5.0-1016-azure`](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#ubuntu-2204)) to bump the ASLR entropy which are discussed here (https://github.com/actions/runner-images/issues/9491#issuecomment-1989718917), i.e. https://github.com/llvm/llvm-project/commit/fb77ca05ffb4f8e666878f2f6718a9fb4d686839, which went into LLVM 17.0.0. 

Note that LeakSanitizer was also impacted, which was fixed in https://github.com/llvm/llvm-project/commit/5ffe955570a5d743bbbae204ce1b132e89fa86dc which also made it into LLVM 17.0.0.

For completeness, here is the commit in the Ubuntu kernel repo which made the changes to `ARCH_MMAP_RND_BITS`: [6b522637c6a7dabd8530026ae933fb5ff17e877f](https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/jammy/commit/?h=hwe-6.5-next--2024.03.04-1--auto&id=6b522637c6a7dabd8530026ae933fb5ff17e877f) (and associated Launchpad bug: [`#1983357`](https://bugs.launchpad.net/ubuntu-kernel-tests/+bug/1983357)). This change was propagated to the `linux-azure-6.5` repository, which is the source repo for the Azure-infused kernel used by the GitHub actions image, in [ff755408f6f81000a45e2b2e54a15a28d6a8cff2](https://git.launchpad.net/ubuntu/+source/linux-azure-6.5/commit/?h=applied/ubuntu/jammy-security&id=ff755408f6f81000a45e2b2e54a15a28d6a8cff2).

Finally, note that the Ubuntu GCC package was updated yesterday to include the LLVM patch for ASan: [6c5be2a496335c513dbe6fa85df2402cfc0f0a8b](https://git.launchpad.net/ubuntu/+source/gcc-13/commit/?id=6c5be2a496335c513dbe6fa85df2402cfc0f0a8b). However, this package is not used for the GCC 13.1.0 compiler available in the `ubuntu-22.04` GitHub Actions image, the image uses the ["Toolchain test build" PPA](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test), [[source]](https://github.com/actions/runner-images/blob/2eee3a2d6a2268795c1b9bf10a75cecac03ddc7d/images/ubuntu/scripts/build/install-gcc-compilers.sh#L11-L13), which as of this writing [has not been updated yet](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test/+packages?field.name_filter=gcc-13&field.status_filter=published&field.series_filter=).

**Comment by andy5995** [comment]
>with GCC 13 (but not Clang 18!) looping runtime error `AddressSanitizer:DEADLYSIGNAL?` and then timing out.

This is happening to me, too, but with gcc 11 (and now 13, which I am trying after seeing this ticket).

CI tests that were passing are now suddently failing. With clang, I don't get an endless loop as mentioned above, but some units tests are failing. Sometimes 
they are different units tests that fail, sometimes they pass. Usually they all pass.

https://github.com/andy5995/canfigger/actions/runs/8312710880/job/22747867106
[logs_21799559162.zip](https://github.com/actions/runner-images/files/14626111/logs_21799559162.zip)

https://github.com/theimpossibleastronaut/rmw/actions/runs/8312663731/job/22747768800

https://productionresultssa5.blob.core.windows.net/actions-results/5ec2690f-2ed9-4417-88c4-c3575b6db226/workflow-job-run-c4625b57-391a-5be5-f30a-26a1e0a53cce/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-03-17T03%3A54%3A16Z&sig=%2BMP9BSQPY1ljAAZVEsYWSsdEC2YR3vnjvz7kDZDQDG8%3D&sp=r&spr=https&sr=b&st=2024-03-17T03%3A44%3A11Z&sv=2021-12-02

**Comment by mikhailkoliada** [comment]
Duplicate of https://github.com/actions/runner-images/issues/9491

**Comment by phil-blain** [comment]
I don't think it's possible to request the older image. In the mean time, the workaround is (cf https://github.com/actions/runner-images/issues/9491#issuecomment-1989718917)

```yaml
    - name: Fix kernel mmap rnd bits
      # Asan in llvm 14 provided in ubuntu 22.04 is incompatible with
      # high-entropy ASLR in much newer kernels that GitHub runners are
      # using leading to random crashes: https://reviews.llvm.org/D148280
      run: sudo sysctl vm.mmap_rnd_bits=28
```

**Comment by hartwork** [comment]
> In the mean time, the workaround is (cf [#9491 (comment)](https://github.com/actions/runner-images/issues/9491#issuecomment-1989718917))
> 
> ```yaml
>     - name: Fix kernel mmap rnd bits
>       # Asan in llvm 14 provided in ubuntu 22.04 is incompatible with
>       # high-entropy ASLR in much newer kernels that GitHub runners are
>       # using leading to random crashes: https://reviews.llvm.org/D148280
>       run: sudo sysctl vm.mmap_rnd_bits=28
> ```

@phil-blain from what I can see, this seems to work well. Thank you!

> I don't think it's possible to request the older image. 

That's a design problem then that will need fixing mid-term. I'll try to come up with a dedicated issue explaining why the current updating and magically moving images is a maintenance nightmare on the GitHub Actions user side of things for a while already.
