### ISSUE TITLE
Ability to build self hosted runners images as docker

### ISSUE THREAD

**Issue by israelshenkar** [actions/runner-images#9671]
### Description

we want to use the ubuntu-latest as a self hosted runners, as it contains all ready all relevant packages.

when trying to build it as in: https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md
you must have azure account.

we would like to create it as docker image.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Ubuntu2204

### Is it regression?

no

### Expected behavior

ability to create the image as docker image

### Actual behavior

using packer to build image.

### Repro steps

follow the steps in: https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md

**Comment by erik-bershel** [comment]
Hey @israelshenkar!
We do not plan to support building Docker images based on our repository. We will definitely release an announcement if such plans appear. Until then, you can only provide such edits completely on your own.

Separately, I note that creating a similar Docker container will be very difficult, if not impossible, due to some features of containers and the number of changes that will need to be made.
