### ISSUE TITLE
Provide labels with architecture information

### ISSUE THREAD

**Issue by agateau-gg** [actions/runner-images#9673]
### Description

With the arrival of ARM-based macOS runners (and maybe ARM-based Linux runners?), it would be helpful to have labels with the process architecture in them, so one could use `macos-latest-arm64` or `linux-latest-x86_64`.

This would avoid surprises like the `macos-latest` switching from x86_64 to arm64.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

-

### Is it regression?

no

### Expected behavior

Have a way to pin the architecture of a runner.

### Actual behavior

No way to pin the architecture of a runner.

### Repro steps

- Use `macos-latest`. Note it's x86_64.
- Wait for the ongoing runner deployment to finish.
- `macos-latest` is now arm64.

**Comment by erik-bershel** [comment]
Hey @agateau-gg!
Any user can view the available runners and corresponding labels on the project's [main page](https://github.com/actions/runner-images?tab=readme-ov-file#available-images). We notify users of any changes of this kind in advance using [announcements](https://github.com/actions/runner-images/issues?q=is%3Aopen+is%3Aissue+label%3AAnnouncement). They same info could be found in GitHub blog as I remember.

For `macOS` images, the basic architecture starting from `macOS-14` will indeed be `arm64`. Mainly due to the fact that Apple has actually doing it (already did I may say). https://www.apple.com/newsroom/2020/06/apple-announces-mac-transition-to-apple-silicon/

**Comment by erik-bershel** [comment]
> Does this mean there is no plan to provide a way to select the architecture of a runner?

Why not? There are both `arm64` and `x86_64` based images available. Intel-based macOS-14 image available under `macos-14-large` label. In the near future it will be also available via `macos-latest-large`.

**Comment by agateau-gg** [comment]
> Why not? There are both arm64 and x86_64 based images available. Intel-based macOS-14 image available under macos-14-large label. In the near future it will be also available via macos-latest-large.

That's nice, but what I meant is a way to be more explicit about it. I'd rather have my workflow matrix says:

```yaml
matrix:
  os:
    - macos-14-x86_64
    - macos-14-arm64
    - windows-2022
    - ubuntu-22.04
```

Instead of:

```yaml
matrix:
  os:
    # x86_64
    - macos-14-large
    # arm64
    - macos-14
    - windows-2022
    - ubuntu-22.04
```

**Comment by JakeWharton** [comment]
This does not really seem stylistic, but a lack of specificity. Arbitrary combinations of the OS version and running size should not be the sole discriminator for the underlying host architecture. If #5631 happens this problem will expand to plague Linux in addition to MacOS.

**Comment by joffrey-bion** [comment]
I have to say I would really need this as well, and it's really not cosmetic. This applies not only to architectures, but other things like nested-virtualization, etc.

The best IMO would be to have separate labels, not just shove everything into a single name. I don't use self-hosted runners but, according to the docs, this is already available for self-hosted runners. Why aren't Github-hosted runners tagged as well using multiple labels?

I wish I could just say:
* `runs-on: [macos, x86_64]`
* `runs-on: [macos, nested-virtualization]`
* `runs-on: [macos, large]`

All 3 might give the same image right now, but it's definitely not the same meaning at all. It would not only help with transitions (leaving GitHub free to make lots of changes to images, because the contract is still respected), but also with maintainability of workflows.
