### ISSUE TITLE
ITMS-90725: App Store will require iOS 17 SDK or later to upload apps

### ISSUE THREAD

**Issue by y-chen** [actions/runner-images#9678]
### Description

Hi all,

We are using `macos-latest` to build and upload an iOS app. The workflow is successful but we receive this warning email from Apple:

> Hello,
>
> We noticed one or more issues with a recent delivery for the following app:
>
> [omiss]
> Version 1.27.0
> Build 75
>
> Although delivery was successful, you may want to correct the following issues in your next delivery. Once you've corrected the issues, upload a new binary to App Store Connect.
>
> ITMS-90725: SDK version issue - This app was built with the iOS 16.2 SDK. Starting April 29, 2024, all iOS and iPadOS apps must be built with the iOS 17 SDK or later, included in Xcode 15 or later, in order to be uploaded to App Store Connect or submitted for distribution.
>
> Apple Developer Relations

Is it planned an update of the runner so it can still be used to upload to the App Store?

Thank you

YIyi Chen

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

No, I just run job with runner `macos-latest`.

### Is it regression?

No

### Expected behavior

Build with iOS 17 SDK.

### Actual behavior

Build with iOS 16.2 SDK.

### Repro steps

Upload app to Apple Store Connect using `macos-latest` runner.

**Comment by erik-bershel** [comment]
Hey @y-chen!

We are in progress of migration for label `macos-latest` from `macOS-12` `x86_64` image to `macOS-14` `arm64` image.

Details: https://github.com/actions/runner-images?tab=readme-ov-file#planned--ongoing-migrations

What does it means? This means that currently runs using the `macos-latest` label end up in the `macOS-12` runners, but over the next 12 weeks or so, more and more runs using the `macos-latest` label will end up in the `macOS-14-arm64` runners.

`macOS-12` runners cannot provide required SDK due to Apple software support policy, only `macOS-14` based runners fit latest `Xcode 15.3`. During the migration you may use `macos-14` label to avoid inconsistency and to use runner with the latest iOS SDK.

**Comment by y-chen** [comment]
Hi @erik-bershel,

using `macos-14` worked!.

Thank you!
