### ISSUE TITLE
The request was cancelled by the remote provider

### ISSUE THREAD

**Issue by ramkia613** [actions/runner-images#9807]
### Description

Hi

GitHub actions jobs on my pipeline is canceled. 

Note that some of the steps passed, and it's being canceled in the middle.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/dee-money/passenger-android/actions/runs/8996691449/attempts/1

### Is it regression?

no

### Expected behavior

Job should pass

### Actual behavior

Job starts, runs for quite a long time, part of the steps some job passed, and then in one of the steps is shown as "canceled".

### Repro steps

It's a private repo

**Comment by shamil-mubarakshin** [comment]
Hey @ramkia613, we will take a look

**Comment by Alexey-Ayupov** [comment]
Hello @ramkia613, We have checked the logs and found out that your run `https://github.com/dee-money/passenger-android/actions/runs/8996691449/attempts/1` exhaust all available CPU and disk thruput resources on the runner.

In this case you have a several options:
1) Adjust your workflow to minimize CPU and disk write operation load
2) Switch to the [larger runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners)
3) Set up your own [self-hosted runner](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners)

We will close this issue since we cannot do much about it, however if you have any other questions feel free to reach us.
