### ISSUE TITLE
Unable to get MSVC++ used as compiler under windows

### ISSUE THREAD

**Issue by kif** [actions/runner-images#9894]
### Description

While setting `cibuildwheel` to build the weels for the release of pyFAI, I found the binaries to be unusable.
This comes down to the compiler used, i.e. gcc-12 instead of msvc++.
https://github.com/silx-kit/pyFAI/actions/runs/9131031831/job/25109335927

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/silx-kit/pyFAI/actions/runs/9131031831/job/25109335927

The build is not failing but the compiler used is the wrong one

### Is it regression?

Since I am setting up this CI, no idea

### Expected behavior

I would expect the default compiler to be used under windows to be MSVC++

### Actual behavior

The compiler used on windows is gcc-12. While it works, it produces binaries which are not usable for a release.

### Repro steps

-

**Comment by erik-bershel** [comment]
Hey @kif!

I'm not sure that the stated behaviour should be the default behaviour since we've never declared a default compiler for C/C++. For your CI if you wish to set MSVC++ compiler you may set it up via `shell` or by using external action [ilammy/msvc-dev-cmd](https://github.com/ilammy/msvc-dev-cmd). Something like this I suppose should work according to the [doc](https://github.com/ilammy/msvc-dev-cmd?tab=readme-ov-file#reconfiguration):
```yml
      - name: Configure build for amd64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64 ## <-- You need to choose desired platform target here
```

I'll close this item for now since it doesn't look like an image bug, but if you have problems setting up the compiler, be sure to ping me - I'll be happy to try to help.

**Comment by kif** [comment]
Thanks a lot, it works now
