### ISSUE TITLE
sg and newgrp require password to run

### ISSUE THREAD

**Issue by bwrsandman** [actions/runner-images#9932]
### Description

Starting with ubuntu 24.04, the `sg` command (like `sudo` but for groups), to run a command as a member of a group either stall (in an action) or error out (in a run statement) while waiting for password input.

Note that the password can be bypassed by adding `runner` to any group using `sudo` then running `sudo -u runner` instead of `sg`

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240516.4.0

https://github.com/bwrsandman/test-runners-sg/actions/runs/9229583904/job/25396063410

### Is it regression?

Yes between 22.04 and 24.04, not 24.04 image versions

### Expected behavior

Like `sudo`, `sg` and ` newgrp` should run without prompting for passwords

### Actual behavior

sg and newgrp both expect user input for passwords.
If run from bash, this errors out immediately but with some actions this will run until the test times out.

### Repro steps

In an action and as run steps:
1. add a group
2. add user to the group
3. run `sg new_group -c groups` or `newgrp new_group`

**Comment by mikhailkoliada** [comment]
It looks like weird ubuntu bug itself. whenever I do add a new group via the `groupadd` command the `/etc/ghshodow` file does not indicate the presence of the password in the file (well, that's what I literally expect). We do not modify/patch shadow files behaviour anyhow in the runner that is why I think it is somewhat to be fixed in ubuntu itself, the only workaround I can offer is to emulate the password removal from the group as if it were present, namely:

```
- name: pre-fix
        run: |
          sudo groupadd mikhailkoliada
          sudo gpasswd -a runner mikhailkoliada
          sudo gpasswd -r mikhailkoliada
          newgrp mikhailkoliada
```
if I perform the `gpasswd -r` command to pretend I want to remove the password, subsequent `newgrp` call goes flawlessly, if I do not call this command, it indeed wants the group password to be entered. Currently we are unable to offer more help.
