### ISSUE TITLE
Update Azure PowerShell Modules

### ISSUE THREAD

**Issue by YanaXu** [actions/runner-images#9980]
### Tool name

Azure PowerShell

### Tool license

same as old versions

### Add or update?

- [ ] Add
- [X] Update

### Desired version

12.0.0

### Brief description of tool

There are 2 requirements in this issue:

- Remove powershell module AzureRM. It's officially retired. Refer to [AzureRM PowerShell module retirement overview](https://learn.microsoft.com/en-us/powershell/azure/azurerm-retirement-overview?view=azps-12.0.0).
- Upgrade Azure PowerShell module (Az) to the latest version *12.0.0*.

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by ijunaidm** [comment]
@YanaXu  - We are looking into this issue, we will update you on this issue.

**Comment by ijunaidm** [comment]
@YanaXu - Unfortunately, we do not have plans to preinstall the latest versions of AZ module due to maintenance concerns and to avoid potential customer impact. We recommend to use [AzurePowerShell@5](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-powershell-v5?view=azure-pipelines) Azure DevOps task or [Azure powershell](https://github.com/Azure/powershell) action for Github Actions to install required versions in runtime.
Thank you for understanding and sorry for the inconvenience!

**Comment by YanaXu** [comment]
> @YanaXu - Unfortunately, we do not have plans to preinstall the latest versions of AZ module due to maintenance concerns and to avoid potential customer impact. We recommend to use [AzurePowerShell@5](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-powershell-v5?view=azure-pipelines) Azure DevOps task or [Azure powershell](https://github.com/Azure/powershell) action for Github Actions to install required versions in runtime. Thank you for understanding and sorry for the inconvenience!

Hi @ijunaidm , I do notice that you have preinstalled the Az 11.3.1. Before that, it's 9.3.0.
May I ask the policy to update Azure PowerShell version?
And I'd like to know if you have the plan to uninstall AzureRM (including the cached ones)?

**Comment by YanaXu** [comment]
@ijunaidm , could you check my questions above? Thanks!

**Comment by olegd-superoffice** [comment]
According to [Windows2022-Readme](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#powershell-modules)

> Azure PowerShell module 2.1.0 and AzureRM PowerShell module 2.1.0 are installed
> and are available via 'Get-Module -ListAvailable'.
> All other versions are saved but not installed.

So `Az: 11.3.1` is available as saved in  `C:\Modules` but not installed. Why it cannot be upgraded to 12.x ? If that's not possible, then maybe 12.x can be added to the list of saved modules?

**Comment by ijunaidm** [comment]
@olegd-superoffice - Yes, we will be upgrading Azure power shell module (Az) to 12.1.0 .
@YanaXu - We will be updating it to 12.1.0.
I will keep you posted about the details after updates are done on our images.

**Comment by ijunaidm** [comment]
@YanaXu - We have started updating the Azure PowerShell module (Az) version to 12.1.0 this week on windows images. 
So it should be available on next week early monday morning. 
But for MacOS and Ubuntu images we will try to update it next week .

**Comment by ijunaidm** [comment]
@YanaXu - For all the ubuntu images and windows 22 image ->  Az Power Shell module version is updated to 12.1.0 
This week it will be implemented on windows 19 image.

**Comment by ijunaidm** [comment]
@YanaXu - And for the first part of the request : Remove powershell module AzureRM -> We won't do it because of breaking changes. We will make sure that we don't install AzureRM on next Windows Server image release. 

For the second part of the request : Upgrade Azure PowerShell module (Az) to the
latest version 12.0.0.-> For all the Ubuntu , Windows and MacOS images Az Power Shell module is updated . 

Thank you.
